---
settings:
  name: Enterprise applications
  search: ontap-technical-reports, ontap-apps-dbs, netapp-solutions-sap
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Applicazioni aziendali
    url: "/index.html"
  - section: mssql
  - section: mysql
  - section: oracle
  - section: postgres
  - title: SAP
    entries:
    - title: SAP HANA e AnyDB
      url: sap-solutions.html
  - section: vmware
  - title: Note legali
    url: "/legal-notices.html"
