---
sidebar: sidebar 
permalink: oracle/virtualization/intro.html 
keywords: oracle, database, ontap, virtualization, esx, hyper-v, KVM 
summary: Introduzione alla virtualizzazione del database 
---
= Virtualizzazione
:allow-uri-read: 


[role="lead"]
La virtualizzazione dei database con VMware ESX, Oracle OVM o KVM è una scelta sempre più comune per i clienti NetApp che hanno scelto la virtualizzazione anche per i database mission-critical.

Esistono numerosi preconcetti sui criteri di supporto per la virtualizzazione, in particolare per i prodotti VMware. In effetti, non è raro che Oracle non supporti in alcun modo la virtualizzazione. Questa nozione non è corretta e causa la perdita di opportunità per la virtualizzazione. Oracle Doc ID 249212,1 descrive i problemi noti in un ambiente Oracle e specifica anche il supporto per RAC.

A un cliente con un problema sconosciuto a Oracle potrebbe essere richiesto di riprodurre il problema su hardware fisico. Un cliente Oracle che utilizza una versione all'avanguardia di un prodotto potrebbe non voler utilizzare la virtualizzazione a causa della possibilità di individuare nuovi bug. Tuttavia, questa situazione non ha rappresentato un problema nella pratica per i clienti che utilizzano versioni di prodotti generalmente disponibili.



== Presentazione storage

I clienti che stanno considerando la virtualizzazione dei propri database devono basare le proprie decisioni di storage sulle esigenze aziendali. Sebbene questa affermazione sia generalmente vera per tutte le decisioni IT, è particolarmente importante per la virtualizzazione, poiché le dimensioni e l'ambito dei progetti variano notevolmente.

Sono disponibili quattro opzioni di base per la presentazione dello storage:

* LUN iSCSI gestite dall'iniziatore iSCSI sulla macchina virtuale, non dall'hypervisor
* File system NFS montati dalla macchina virtuale, non su disco della macchina virtuale (VMDK)
* Datastore di hypervisor


In generale, evitare di utilizzare datastore per file Oracle. Questa raccomandazione è motivata da numerosi motivi:

* *Trasparenza.* quando una VM possiede i propri file system, è più facile per un amministratore di database o un amministratore di sistema identificare l'origine dei file system per i propri dati.
* *Performance.* i test hanno dimostrato che esiste un effetto sulle prestazioni derivante dal canale di tutti i/o attraverso un archivio dati di hypervisor.
* *Gestibilità.* quando una VM possiede i propri file system, l'utilizzo o il mancato utilizzo di un livello di hypervisor influisce sulla gestibilità. È possibile utilizzare le stesse procedure per il provisioning, il monitoraggio, la protezione dei dati e così via nell'intero ambiente, inclusi ambienti virtualizzati e non.
* *Stabilità e risoluzione dei problemi.* quando una VM possiede i propri file system, fornire prestazioni buone e stabili e risolvere i problemi sono molto più semplici perché l'intero stack di storage è presente sulla VM. L'unico ruolo dell'hypervisor è il trasporto di frame FC o IP. Quando un datastore è incluso in una configurazione, complica la configurazione introducendo un altro insieme di timeout, parametri, file di log e potenziali bug.
* *Portabilità.* quando una VM è proprietaria dei suoi file system, il processo di spostamento di un ambiente Oracle diventa molto più semplice. I file system possono essere spostati facilmente tra guest virtualizzati e non.
* *Vendor lock-in.* dopo il posizionamento dei dati in un datastore, utilizzando un hypervisor diverso o estraendo i dati dall'ambiente virtualizzato diventa del tutto molto difficile.
* *Abilitazione snapshot.* in alcuni casi, i backup in un ambiente virtualizzato possono diventare un problema a causa della larghezza di banda relativamente limitata. Ad esempio, un trunk 10GbE a quattro porte potrebbe essere sufficiente per supportare le esigenze quotidiane di prestazioni di molti database virtualizzati. Tuttavia, tale trunk non sarebbe sufficiente per eseguire backup utilizzando RMAN o altri prodotti di backup che richiedono lo streaming di una copia di dimensioni complete dei dati.
+
L'utilizzo di file system proprietari di VM semplifica l'utilizzo di backup e ripristini basati su Snapshot. Un file system di proprietà delle macchine virtuali alleggerisce il carico del lavoro di esecuzione dei backup nel sistema storage. Non è necessario esagerare la configurazione dell'hypervisor solo per supportare i requisiti di larghezza di banda e CPU nella finestra di backup.




TIP: *NetApp consiglia* di evitare di posizionare i dati Oracle in un datastore per ottenere performance e gestibilità ottimali. Utilizzare file system di proprietà dei guest, come file system NFS o iSCSI, gestiti dal guest o con RDM.



== Driver paravirtualizzati

Per prestazioni ottimali, l'uso di driver di rete paravirtualizzati è fondamentale. Quando si utilizza un datastore, è necessario un driver SCSI paravirtualizzato. Un driver di dispositivo paravirtualizzato consente a un guest di integrarsi più profondamente nell'hypervisor, invece di un driver emulato in cui l'hypervisor spende più tempo CPU che imita il comportamento dell'hardware fisico.

Le performance della maggior parte dei database sono limitate dallo storage. Pertanto, la latenza supplementare introdotta da un driver di rete o SCSI è particolarmente evidente. L'assistenza clienti NetApp ha riscontrato molti problemi di prestazioni risolti installando driver paravirtualizzati. Durante una proof of concept realizzata da un cliente, i database hanno mostrato prestazioni migliori con ESX rispetto alla stessa apparecchiatura hardware in esecuzione come bare metal. I test richiedevano molto i/o e la differenza di prestazioni veniva attribuita all'utilizzo dei driver di rete paravirtualizzati ESX.


TIP: *NetApp consiglia* di utilizzare sempre driver di rete paravirtualizzati e driver SCSI.



== Overcommit RAM

L'overcommit della RAM implica la configurazione di una quantità di RAM virtualizzata su vari host superiore a quella presente sull'hardware fisico. In caso contrario, si potrebbero verificare problemi di prestazioni imprevisti. Quando si virtualizza un database, i blocchi sottostanti di Oracle SGA non devono essere sostituiti con lo storage dall'hypervisor. Ciò causa risultati di prestazioni altamente instabili.


TIP: *NetApp consiglia* di non configurare un hypervisor in modo da consentire lo scambio dei blocchi SGA di Oracle.
