---
sidebar: sidebar 
permalink: oracle/oracle-storage-san-config-lun-alignment.html 
keywords: SAN, ASM, LVM 
summary: Allineamento di LUN con i database Oracle 
---
= Allineamento LUN per l'i/o del database Oracle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'allineamento delle LUN si riferisce all'ottimizzazione dell'i/o in relazione al layout del file system sottostante.

Direttiva non risolta in <stdin> - include::lun-alignment.adoc[]

Vedere anche la discussione sull'allineamento dei blocchi di compressione nella sezione link:oracle-ontap-config-efficiency.html["Efficienza"]. Qualsiasi layout allineato ai limiti del blocco di compressione 8KB è allineato ai limiti 4KB.



== Avvertenze di disallineamento

Direttiva non risolta in <stdin> - include::database-misalignment-warnings.adoc[]

L'allineamento negli ambienti Solaris è più complicato. Fare riferimento a. http://support.netapp.com/documentation/productlibrary/index.html?productID=61343["Configurazione host SAN ONTAP"^] per ulteriori informazioni.

|===
| Attenzione 


| Negli ambienti Solaris x86, prestare ulteriore attenzione al corretto allineamento poiché la maggior parte delle configurazioni prevede diversi livelli di partizioni. Le sezioni di partizione di Solaris x86 si trovano solitamente in cima a una tabella di partizioni del record di avvio master standard. 
|===