---
sidebar: sidebar 
permalink: oracle/oracle-tiering-whole-file.html 
keywords: tiering, fabricpool 
summary: Tiering completo delle sezioni Oracle 
---
= Tiering completo dei file Oracle
:allow-uri-read: 


[role="lead"]
Anche se il tiering FabricPool opera a livello di blocco, in alcuni casi può essere utilizzato per fornire un tiering a livello di file.

Molti set di dati delle applicazioni sono organizzati per data e tali dati hanno generalmente sempre meno probabilità di accedere man mano che invecchiano. Ad esempio, una banca potrebbe avere un archivio di file PDF che contengono cinque anni di dichiarazioni dei clienti, ma solo gli ultimi mesi sono attivi. FabricPool può essere utilizzato per spostare i file di dati meno recenti nel Tier di capacità. Un periodo di raffreddamento di 14 giorni garantirebbe che i 14 giorni più recenti di file PDF rimangano sul livello di prestazioni. Inoltre, i file letti almeno ogni 14 giorni resterebbero hot e quindi nel Tier di performance.



== Policy

Per implementare un approccio di tiering basato su file, è necessario disporre di file scritti e non modificati successivamente. Il `tiering-minimum-cooling-days` i criteri devono essere impostati su un livello sufficientemente alto da mantenere i file di cui potresti aver bisogno nel tier di performance. Ad esempio, un set di dati per il quale sono necessari gli ultimi 60 giorni di dati con performance ottimali garantisce la definizione di `tiering-minimum-cooling-days` periodo a 60. Risultati simili possono essere ottenuti anche in base ai modelli di accesso ai file. Ad esempio, se sono necessari gli ultimi 90 giorni di dati e l'applicazione sta accedendo a quell'arco di dati di 90 giorni, i dati resteranno sul Tier di performance. Impostando `tiering-minimum-cooling-days` a 2, si ottiene un tiering prompt dopo che i dati sono meno attivi.

Il `auto` la policy è necessaria per gestire il tiering di questi blocchi perché solo l' `auto` il criterio influisce sui blocchi che si trovano nel file system attivo.


NOTE: Qualsiasi tipo di accesso ai dati ripristina i dati della mappa termica. La scansione virus, l'indicizzazione e persino le attività di backup in grado di leggere i file di origine impediscono il tiering perché è necessario `tiering-minimum-cooling-days` la soglia non viene mai raggiunta.
