---
sidebar: sidebar 
permalink: oracle/oracle-dp-consistency-group-backup.html 
keywords: oracle, data, protection, consistency, group, backup, volume, archive, log, redo, controlfiles 
summary: Backup del gruppo di coerenza per Oracle su ONTAP 
---
= Backup di gruppo di coerenza Oracle
:allow-uri-read: 


[role="lead"]
Per un backup il più semplice possibile, posiziona l'intero database Oracle in un singolo volume.

Proteggere i file di dati, i log di archivio, i log di ripristino e i file di controllo con un'unica istantanea è un metodo di backup, ripristino e replica valido.  Tuttavia, l'RPO è limitato al punto del backup stesso. È adatto per un RPO di un'ora o superiore. Se un database si estende su volumi, è necessario creare snapshot cg utilizzando uno degli strumenti descritti in precedenza.

Ad esempio, l'intero database può trovarsi in un singolo volume con la seguente pianificazione degli snapshot:

* 72 snapshot ogni ora
* 30 istantanee notturne
* 12 snapshot mensili


Questo garantisce un RPO di un'ora nel periodo corrente delle 72 ore precedenti, più backup notturni e mensili aggiuntivi. È possibile includere più database o file applicativi nel singolo volume o set di snapshot cg per offrire backup coerenti in un ambiente più ampio.
