---
sidebar: sidebar 
permalink: oracle/oracle-ontap-config-capacity-limits.html 
keywords: capacity 
summary: Capacità e spazio libero per database e storage ONTAP 
searchtitle: Gestione della capacità dello storage e dei database Oracle 
---
= Gestione della capacità
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La gestione di un database o di un'altra applicazione aziendale con storage aziendale prevedibile, gestibile e ad alte prestazioni richiede spazio libero sulle unità per la gestione di dati e metadati. La quantità di spazio libero richiesta dipende dal tipo di unità utilizzata e dai processi aziendali.

Lo spazio libero è definito come qualsiasi spazio non utilizzato per dati effettivi e include lo spazio non allocato sull'aggregato stesso e lo spazio non utilizzato all'interno dei volumi costituenti. Occorre inoltre considerare il thin provisioning. Ad esempio, un AFF volume potrebbe contenere una LUN da 1TB di cui solo il 50% è utilizzato da dati effettivi. In un ambiente con thin provisioning, questo sembrerebbe correttamente consumare 500GB di spazio. Tuttavia, in un ambiente con provisioning completo, l'intera capacità di 1TB sembra essere in uso. I 500GB di spazio non allocato sono nascosti. Questo spazio non viene utilizzato da dati effettivi e dovrebbe quindi essere incluso nel calcolo dello spazio libero.

Di seguito sono riportate le raccomandazioni NetApp per i sistemi storage utilizzati per le applicazioni aziendali:



== Aggregati SSD AFF e zone di disponibilità di archiviazione ASA


TIP: *NetApp consiglia* almeno il 10% di spazio libero. Ciò comprende tutto lo spazio inutilizzato, compreso lo spazio libero all'interno dell'aggregato o di un volume ed eventuale spazio libero allocato a causa dell'utilizzo del provisioning completo, ma non utilizzato dai dati effettivi. Lo spazio logico non è importante, la domanda è quanto spazio fisico libero effettivo è disponibile per lo storage dei dati.

Il consiglio di liberare il 10% dello spazio è molto conservativo. Gli aggregati SSD possono supportare i carichi di lavoro a livelli di utilizzo ancora più elevati senza influire sulle performance. Tuttavia, con l'aumento dell'utilizzo dell'aggregato, aumenta anche il rischio di esaurimento dello spazio se l'utilizzo non viene monitorato con attenzione. Inoltre, mentre si utilizza un sistema al 99% della capacità potrebbe non verificarsi un peggioramento delle performance, tuttavia si verificherebbe un sforzo di gestione che impedirebbe il riempimento completo del sistema mentre si ordina hardware aggiuntivo e potrebbe essere necessario del tempo per l'acquisto e l'installazione di dischi aggiuntivi.



== Aggregati HDD, compresi gli aggregati Flash Pool


TIP: *NetApp consiglia* almeno il 15% di spazio libero quando si utilizzano unità rotanti. Ciò comprende tutto lo spazio inutilizzato, compreso lo spazio libero all'interno dell'aggregato o di un volume ed eventuale spazio libero allocato a causa dell'utilizzo del provisioning completo, ma non utilizzato dai dati effettivi. Le prestazioni saranno influenzate dall'avvicinarsi del 10% dello spazio libero.
