---
sidebar: sidebar 
permalink: oracle/oracle-network-config-direct-connect.html 
keywords: direct-connect, oracle 
summary: Database Oracle e connettività ONTAP a collegamento diretto 
searchtitle: Database Oracle e connettività ONTAP a collegamento diretto 
---
= Connessione di rete diretta
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Gli amministratori di sistema a volte preferiscono semplificare le proprie infrastrutture rimuovendo gli switch di rete dalla configurazione. Questo permette di creare una soluzione più autonoma con meno componenti e meno spazio richiesto nel rack. Ci sono alcune importanti limitazioni che dipendono dal protocollo in uso.



=== Fibre Channel

A partire da ONTAP 9.19.1, la connessione FC diretta è supportata sia con FC-SAN tradizionale (SCSI) che con NVMe/FC con specifici adattatori FC del sistema storage. Gli HBA stabiliranno una connessione FC punto-punto standard.

Prima di ONTAP 9.19.1, i sistemi storage ONTAP richiedono NPIV, il che significa che il sistema storage deve essere connesso a uno switch FC che supporta anch'esso NPIV.



=== ISCSI e NVMe/TCP

Un host che utilizza iSCSI o NVMe/TCP può essere collegato direttamente a un sistema storage e funzionare normalmente. La ragione è la pedata. Le connessioni dirette a due storage controller differenti offrono due percorsi indipendenti per il flusso di dati. La perdita di percorso, porta o controller non impedisce l'utilizzo dell'altro percorso.



=== NFS

È possibile utilizzare lo storage NFS con connessione diretta, ma con una limitazione significativa: Il failover non funzionerà senza una significativa attività di scripting, che sarà responsabilità del cliente.

Il motivo per cui il failover senza interruzioni è complicato con lo storage NFS connesso direttamente è il routing che si verifica sul sistema operativo locale. Ad esempio, si supponga che un host abbia un indirizzo IP 192.168.1.1/24 e che sia collegato direttamente a un controller ONTAP con un indirizzo IP 192.168.1.50/24. Durante il failover, l'indirizzo 192.168.1.50 può eseguire il failover sull'altro controller e sarà disponibile per l'host, ma in che modo l'host rileva la sua presenza? L'indirizzo 192.168.1.1 originale esiste ancora sulla scheda di rete host che non si connette più a un sistema operativo. Il traffico destinato a 192.168.1.50 continuerebbe ad essere inviato a una porta di rete inutilizzabile.

La seconda scheda di rete del sistema operativo potrebbe essere configurata come 192.168.1.2 e sarebbe in grado di comunicare con l'indirizzo 192.168.1.50 che è passato in failover, ma le tabelle di routing locali avrebbero come impostazione predefinita l'utilizzo di un *e un solo* indirizzo per comunicare con la sottorete 192.168.1.0/24. Un sysadmin potrebbe creare un framework di script che rileva una connessione di rete non riuscita e modifica le tabelle di routing locali oppure attiva e disattiva le interfacce. La procedura esatta dipenderebbe dal sistema operativo in uso.

In pratica, i clienti NetApp dispongono di NFS con connessione diretta, ma in genere solo per i workload in cui le pause io durante i failover sono accettabili. Quando si utilizzano i supporti rigidi, non devono verificarsi errori di i/o durante tali pause. L'io dovrebbe bloccarsi finché i servizi non vengono ripristinati, mediante failback o intervento manuale, per spostare gli indirizzi IP tra le schede NIC dell'host.
