---
sidebar: sidebar 
permalink: oracle/oracle-asar2-app-config-block-sizes.html 
keywords: oracle, database, ASA r2, ontap, SAN, ASM, blocks 
summary: Dimensioni dei blocchi del database Oracle con ASA r2 
searchtitle: Dimensioni dei blocchi del database Oracle con ASA r2 
---
= Dimensioni dei blocchi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP utilizza internamente una dimensione di blocco variabile, il che significa che i database Oracle possono essere configurati con qualsiasi dimensione di blocco desiderata. Tuttavia, le dimensioni dei blocchi del file system possono influire sulle prestazioni e, in alcuni casi, una dimensione maggiore del blocco redo può migliorare le prestazioni.

ASA r2 non introduce alcuna modifica alle raccomandazioni sulle dimensioni dei blocchi Oracle rispetto ai sistemi AFF/ FAS . Il comportamento ONTAP rimane coerente su tutte le piattaforme.



== Dimensioni dei blocchi di dati

Alcuni sistemi operativi offrono una scelta di dimensioni dei blocchi del file system. Per i file system che supportano i file di dati Oracle, quando si utilizza la compressione le dimensioni del blocco devono essere pari a 8KB KB. Quando la compressione non è necessaria, è possibile utilizzare dimensioni del blocco pari a 8KB K o 4KB K.

Se un file dati viene inserito in un file system con un blocco di 512 byte, è possibile che i file non siano allineati correttamente. Il LUN e il file system potrebbero essere allineati correttamente in base ai consigli di NetApp, ma l'i/o del file non sarebbe allineato correttamente. Un tale disallineamento causerebbe gravi problemi di prestazioni.



== Ripristina le dimensioni dei blocchi

I file system che supportano i log di ripristino devono utilizzare una dimensione blocco pari a un multiplo della dimensione del blocco di ripristino. In genere, questo richiede che sia il file system del redo log sia il redo log stesso utilizzino una dimensione del blocco di 512 byte.

A velocità di ripristino molto elevate, è possibile che le dimensioni dei blocchi di 4KB KB funzionino meglio, perché alte velocità di ripristino consentono di eseguire l'i/o in un numero inferiore di operazioni più efficienti. Se le velocità di ripristino sono superiori a 50Mbps KB, valutare la possibilità di testare dimensioni blocco di 4KB KB.

Sono stati identificati alcuni problemi dei clienti con i database che utilizzano i log di redo con dimensioni dei blocchi di 512 byte in un file system con dimensioni dei blocchi di 4KB KB e molte transazioni di dimensioni molto ridotte. L'overhead coinvolto nell'applicazione di modifiche multiple a 512 byte a un singolo blocco di file system da 4KB ha portato a problemi di performance che sono stati risolti modificando il file system in modo da utilizzare dimensioni dei blocchi di 512 byte.


TIP: *NetApp consiglia* di non modificare le dimensioni del blocco di redo se non dietro indicazione di un'organizzazione di assistenza clienti o servizi professionali o se la modifica si basa sulla documentazione ufficiale del prodotto.
