---
sidebar: sidebar 
permalink: oracle/oracle-migration-overview.html 
keywords: oracle, ontap, migrations, TR-4534 
summary: Introduzione alla migrazione dello storage Oracle 
---
= Migrazione dei database Oracle sui sistemi di storage NetApp
:allow-uri-read: 


[role="lead"]
L'utilizzo delle funzionalità di una nuova piattaforma di storage impone un requisito inevitabile e prevede il posizionamento dei dati nel nuovo sistema di storage.


NOTE: Questa documentazione sostituisce il report tecnico precedentemente pubblicato _TR-4534: Migrazione dei database Oracle in sistemi di storage NetApp_

Nel caso di un nuovo progetto di database, questo non rappresenta un problema, poiché gli ambienti di database e applicazioni sono stati costruiti in sede. La migrazione, tuttavia, pone sfide speciali in relazione all'interruzione del business, al tempo necessario per il completamento della migrazione, alle competenze necessarie e alla minimizzazione del rischio.



== Script

La presente documentazione contiene script di esempio. Questi script forniscono metodi di esempio per automatizzare vari aspetti della migrazione per ridurre la possibilità di errori da parte degli utenti. Gli script possono ridurre le richieste generali del personale IT responsabile della migrazione e accelerare il processo complessivo. Questi script sono ricavati da progetti di migrazione effettivi eseguiti dai servizi di assistenza professionale NetApp e dai partner NetApp. Nella presente documentazione sono riportati alcuni esempi del loro utilizzo.
