---
sidebar: sidebar 
permalink: oracle/oracle-dp-planning.html 
keywords: data protection, DR, snapshots, CG 
summary: Pianificazione della protezione dei dati per i database Oracle 
searchtitle: Pianificazione della protezione dei dati per i database Oracle 
---
= Pianificazione della protezione dei dati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La corretta architettura di protezione dei dati del database Oracle dipende dai requisiti di business relativi alla conservazione dei dati, alla ripristinabilità e alla tolleranza per le interruzioni durante i vari eventi.

Ad esempio, consideriamo il numero di applicazioni, database e set di dati importanti inclusi nell'ambito della fornitura. La costruzione di una strategia di backup per un singolo set di dati che garantisca la conformità con gli SLA tipici è piuttosto semplice, perché non ci sono molti oggetti da gestire. Con l'aumento del numero di set di dati, il monitoraggio diventa più complicato e gli amministratori potrebbero essere costretti a spendere una crescente quantità di tempo nella risoluzione degli errori di backup. Quando un ambiente raggiunge il cloud e scala un service provider, è necessario un approccio completamente diverso.

Anche le dimensioni del set di dati influiscono sulla strategia. Ad esempio, esistono molte opzioni per il backup e il ripristino con un database da 100GB TB perché il set di dati è così piccolo. La semplice copia dei dati dai supporti di backup con gli strumenti tradizionali in genere offre un RTO sufficiente per il recovery. Un database 100TB ha normalmente bisogno di una strategia completamente diversa, a meno che l'RTO non consenta un'interruzione di più giorni, nel qual caso una tradizionale procedura di backup e ripristino basata sulla copia potrebbe essere accettabile.

Infine, vi sono alcuni fattori che esulano dal processo di backup e ripristino stesso. Ad esempio, esistono database che supportano attività di produzione critiche e che rendono il ripristino una rara eventualità che viene eseguita solo da DBA esperti? In alternativa, i database fanno parte di un grande ambiente di sviluppo in cui il ripristino è un evento frequente e gestito da un team IT generico?



[[is-a-snapshot-a-backup]]
== Uno snapshot è un backup?

Un'obiezione comunemente sollevata all'utilizzo delle snapshot come strategia di protezione dei dati è rappresentata dal fatto che i dati "reali" e i dati snapshot si trovano sugli stessi dischi. La perdita di tali unità causerebbe la perdita sia dei dati primari che del backup.

Si tratta di un problema valido. Le snapshot locali vengono utilizzate per le esigenze di backup e ripristino quotidiane, e in questo senso la snapshot è un backup. Quasi il 99% di tutti gli scenari di ripristino in ambienti NetApp si affida alle snapshot per soddisfare anche i requisiti RTO più aggressivi.

Gli snapshot locali non dovrebbero, tuttavia, mai essere l'unica strategia di backup, ragione per cui NetApp offre tecnologie come la replica SnapMirror per replicare in modo rapido ed efficiente le snapshot su un set indipendente di dischi. In una soluzione adeguatamente progettata con istantanee e replica snapshot, l'utilizzo del nastro può essere ridotto a icona in un archivio trimestrale o eliminato del tutto.



[[crash-consistent-backups]]
== Backup coerenti con il crash

Un backup coerente con il crash prevede l'acquisizione dello stato di un dataset (o di più dataset) in un singolo punto atomico nel tempo. Come esempio di database, questo include tutti i componenti del database, come datafile, file di log e altri file direttamente associati al database. Questo funziona con quasi tutti i prodotti di database relazionali, inclusi Oracle RDBMS, Microsoft SQL Server, SAP HANA, PostgreSQL, MySQL e MariaDB. La protezione di una configurazione VMware con un backup di un gruppo di coerenza sarebbe simile: acquisire tutti i datastore e potenzialmente le LUN di avvio di ESX in un singolo punto atomico nel tempo.

La creazione di un backup di questo tipo simula essenzialmente un crash, motivo per cui tali backup sono chiamati backup coerenti con il crash. A volte sorgono dubbi sul supporto per gli scenari di recovery, ma è importante comprendere che di solito non è necessaria alcuna procedura di recovery. Quando l'applicazione si avvia dopo il ripristino di un backup del gruppo di coerenza, esegue i normali processi di recovery del log, la riproduzione del journal del file system e altre attività per riprodurre qualsiasi I/O che era in corso al momento del backup. L'applicazione si avvia quindi normalmente.

In sostanza, qualsiasi applicazione in grado di resistere a un'interruzione dell'alimentazione o a un arresto anomalo del server senza danneggiamento dei dati può essere protetta in questo modo. Ciò può essere dimostrato anche dal numero elevato di applicazioni protette con prodotti di mirroring sincrono e asincrono di numerosi vendor. Se un disastro colpisce improvvisamente il sito primario, il sito di replica contiene un'immagine coerente dell'ambiente originale al momento del disastro. Ancora una volta, non è necessaria alcuna procedura di recupero speciale.

L'RPO per questo approccio è solitamente limitato al momento del backup. Come regola generale, l'RPO minimo per backup coerente con il crash è di un'ora. Ad esempio, 48 snapshot orari più altri 30 giorni di snapshot notturni sono ragionevoli e non richiederebbero la conservazione di un numero eccessivo di snapshot. Un RPO inferiore a un'ora diventa più difficile da raggiungere e non è consigliato senza prima consultare i NetApp Professional Services per comprendere l'ambiente, la scalabilità e i requisiti di protezione dei dati.

Il tempo di ripristino (RTO) si misura solitamente in secondi. Quando un'applicazione viene arrestata, i volumi NFS, le LUN o gli spazi dei nomi NVMe vengono ripristinati e l'applicazione viene riavviata.

L'approccio più semplice consiste nel posizionare tutti i file o le LUN in un singolo volume AFF o LUN/namespace ASA. Quando un dataset deve estendersi su più risorse di storage, è necessario un gruppo di coerenza. Questo può essere configurato tramite System Manager o chiamate API RESTful, inoltre SnapCenter è in grado di creare un semplice snapshot del gruppo di coerenza.



[[replication-and-disaster-recovery-architecture]]
== Architettura di replica e disaster recovery

Questa sezione riguarda la protezione dei dati remoti, per la quale i dati vengono replicati in un sito remoto ai fini di uno storage offsite sicuro e di un disaster recovery. Si noti che queste tabelle non riguardano la protezione dei dati di mirroring sincrono. Per questo requisito, consultare la documentazione di NetApp MetroCluster tra cui link:oracle-dr-mcc-failover.html["MetroCluster"] e. link:oracle-dr-smas-overview.html["Sincronizzazione attiva di SnapMirror"]

L'RPO di DR è limitato dalla larghezza di banda della rete disponibile e dalle dimensioni totali dei dati da proteggere. Dopo la creazione del trasferimento di base iniziale, gli aggiornamenti si basano solo sui dati modificati, che in genere rappresentano una bassa percentuale dell'impatto totale dei dati, sebbene esistano delle eccezioni.

Ad esempio, un database 10TB con un tasso di modifica settimanale del 10% ha una media di circa 6GB TB all'ora delle modifiche totali. Con 10Gb GB di connettività, il trasferimento di questo database richiede circa sei minuti. Il tasso di modifica varia in base alla fluttuazione del tasso di modifica del database, ma nel complesso dovrebbe essere possibile ottenere un intervallo di aggiornamento di 15 minuti e un RPO di 15 minuti. Se sono presenti 100 database di questo tipo, sono necessari 600 minuti per trasferire i dati. Pertanto, non è possibile un RPO di un'ora. Allo stesso modo, una replica di un singolo database 100TB con un tasso di modifica settimanale del 10% non può essere aggiornata in modo affidabile in un'ora.

Ulteriori fattori possono influenzare la replica, come l'overhead di replica e le limitazioni sul numero di operazioni di replica simultanee. Tuttavia, la pianificazione complessiva per una strategia di replica a risorsa singola può essere basata sulla larghezza di banda disponibile, e un RPO di replica di un'ora è generalmente raggiungibile. Un RPO inferiore a un'ora diventa più difficile da ottenere e dovrebbe essere eseguito solo dopo aver consultato i NetApp Professional Services. In alcuni casi, 15 minuti sono fattibili con un'ottima connettività di rete sito-sito. Tuttavia, in generale, quando è richiesto un RPO inferiore a un'ora, l'architettura di riproduzione dei log multi-risorsa offre risultati migliori.

L'RTO con replica di gruppo di coerenza in uno scenario di disaster recovery è eccellente, generalmente misurato in secondi dal punto di vista dello storage. L'approccio più semplice è quello di rompere il mirror e il database è pronto per essere avviato. Il tempo di avvio del database è generalmente di circa 10 secondi, ma database di grandi dimensioni con molte transazioni registrate potrebbero richiedere alcuni minuti.

Il fattore più importante per determinare l'RTO non è il sistema storage, ma piuttosto l'applicazione e il sistema operativo host in cui viene eseguito. Ad esempio, i dati replicati possono essere resi disponibili in un secondo o due, ma questo rappresenta solo i dati. Deve inoltre essere presente un sistema operativo correttamente configurato con file binari delle applicazioni disponibili per l'utilizzo dei dati.

In alcuni casi, i clienti hanno preparato istanze di disaster recovery in anticipo con lo storage prerilevato sui sistemi operativi. In questi casi, l'attivazione dello scenario di disaster recovery può richiedere solo la rottura di un mirror e l'avvio dell'applicazione. In altri casi, è possibile eseguire il mirroring del sistema operativo e delle applicazioni associate insieme al database come VMDK (ESX Virtual Machine Disk). In questi casi, l'RPO è determinato dall'investimento effettuato da un cliente nell'automazione per l'avvio rapido del VMDK e la possibilità di avviare le applicazioni.

Il tempo di conservazione è in parte controllato dal limite di snapshot. Ad esempio, i volumi AFF e le LUN ASA in ONTAP hanno un limite di 1024 snapshot. In alcuni casi, i clienti hanno utilizzato la replica multiplex per aumentare il limite. Ad esempio, se sono necessari 2000 giorni di backup, una sorgente può essere replicata su due destinazioni diverse con aggiornamenti che avvengono a giorni alterni. Ciò richiede un aumento dello spazio iniziale necessario, ma rappresenta comunque un approccio molto più efficiente rispetto a un sistema di backup tradizionale, che prevede più backup completi.



[[single-volume-consistency-group-aff]]
=== Gruppo di coerenza a volume singolo (AFF)

L'approccio più semplice consiste nel posizionare tutti i file o le LUN in un singolo volume. Un volume è di per sé un gruppo di coerenza, il che significa che gli aggiornamenti SnapMirror e SnapVault possono essere pianificati direttamente sul sistema storage. Non è necessario alcun software esterno.



[[single-lunnamespace-consistency-group-asa]]
=== Gruppo di coerenza LUN/namespace singolo (ASA)

Sebbene possa sembrare strano posizionare un intero database su un singolo LUN/namespace, questa pratica sta diventando sempre più comune. Il motivo per cui i volume manager sono stati originariamente creati era quello di superare i limiti di prestazioni e capacità delle unità fisiche. Con gli array moderni, un singolo dispositivo a blocchi presentato a un host è già astratto su più unità. Le dimensioni possono essere regolate dinamicamente e le prestazioni sono di gran lunga superiori a quelle di una singola unità.

Il risultato è che carichi di lavoro che vanno da un datastore ESX a un database Oracle possono spesso essere ospitati su un singolo dispositivo a blocchi. Ciò non solo semplifica notevolmente la gestione dei dati, ma ha anche effetti collaterali positivi, come tempi di riavvio dell'host più rapidi grazie al numero ridotto di dispositivi da rilevare.



[[multi-volume-consistency-group]]
=== Gruppo di coerenza multi-volume

Quando un database deve estendersi su volumi AFF o LUN/namespace ASA, è necessario uno snapshot del gruppo di coerenza. Come accennato in precedenza, questa operazione può essere configurata tramite System Manager o chiamate API RESTful, inoltre SnapCenter è in grado di creare uno snapshot semplice del gruppo di coerenza.

C'è anche un'ulteriore considerazione da fare sull'utilizzo di snapshot coerenti multi-volume AFF o multi-LUN ASA a scopo di disaster recovery. Quando si esegue un aggiornamento di più relazioni SnapMirror, è possibile che si verifichi un disastro mentre un trasferimento è ancora in corso. Il risultato sarebbe un insieme di volumi, LUN o namespace non coerenti tra loro. Se ciò accadesse, alcuni dei volumi dovrebbero essere ripristinati a uno stato di snapshot precedente per fornire un'immagine del database coerente con il crash e pronta all'uso.



[[disaster-recovery-activation]]
== Disaster recovery: Attivazione



[[nfs]]
=== NFS

Il processo di attivazione della copia di disaster recovery dipende dal tipo di storage. Con NFS, i file system possono essere premontati sul server di disaster recovery. Sono in uno stato di sola lettura e diventano lettura-scrittura quando il mirror è rotto. Ciò offre un RPO estremamente basso e il processo generale di disaster recovery è più affidabile, poiché ci sono meno parti da gestire.



[[san]]
=== SAN

L'attivazione delle configurazioni SAN in caso di disaster recovery diventa più complicata. L'opzione più semplice è in genere quella di rompere temporaneamente i mirror e montare le risorse SAN, tra cui passaggi come il rilevamento della configurazione LVM (incluse funzioni specifiche dell'applicazione come Oracle Automatic Storage Management [ASM]) e l'aggiunta di voci a /etc/fstab.

Il risultato è che i percorsi dei dispositivi LUN, i nomi dei gruppi di volumi e gli altri percorsi dei dispositivi vengono resi noti al server di destinazione. Tali risorse possono quindi essere chiuse e, successivamente, i mirror possono essere ripristinati. Il risultato è un server che si trova in uno stato in grado di portare rapidamente l'applicazione online. I passaggi per attivare gruppi di volumi, montare file system o avviare database e applicazioni sono facilmente automatizzati.

È necessario assicurarsi che l'ambiente di disaster recovery sia aggiornato. Ad esempio, è probabile che vengano aggiunti nuovi LUN al server di origine, il che significa che è necessario rilevare preventivamente i nuovi LUN sulla destinazione per garantire che il piano di disaster recovery funzioni come previsto.
