---
sidebar: sidebar 
permalink: oracle/oracle-dr-snapmirror-basics.html 
keywords: ontap, snapmirror 
summary: SnapMirror e SyncMirror 
---
= SnapMirror e SyncMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Quasi tutte le applicazioni richiedono la replica dei dati.

A livello di base, la replica può significare una copia su nastro archiviata fuori sede o una replica a livello di applicazione in una posizione di standby. Il disaster recovery si riferisce all'utilizzo di queste copie di replica per portare un servizio online in caso di perdita catastrofica del servizio.

ONTAP offre numerose opzioni di replica per soddisfare numerosi requisiti in maniera nativa all'interno dello storage array e soddisfare una vasta gamma di esigenze. Queste opzioni includono la replica semplice dei backup su un sito remoto fino a una soluzione sincrona e completamente automatizzata che fornisce disaster recovery e alta disponibilità nella stessa piattaforma.

Le principali tecnologie di replica ONTAP applicabili alle applicazioni sono le tecnologie SnapMirror e NetApp SyncMirror di NetApp. Non si tratta di prodotti aggiuntivi, bensì di prodotti completamente integrati in ONTAP e attivati tramite la semplice aggiunta di una chiave di licenza. Anche la replica a livello di storage non è l'unica opzione possibile. La replica a livello di applicazione, come ad esempio Oracle DataGuard, può anche integrarsi in una strategia di protezione dei dati basata su ONTAP.

La scelta giusta dipende dai requisiti specifici di replica, recovery e conservazione.



== SnapMirror di ONTAP

SnapMirror è la soluzione di replica asincrona di NetApp, idealmente creata per proteggere set di dati grandi, complicati e dinamici come database e le loro applicazioni associate. I valori chiave sono i seguenti:

* *Gestibilità.* SnapMirror è facile da configurare e gestire perché è una parte nativa del software di storage. Non sono richiesti prodotti aggiuntivi. Le relazioni di replica possono essere stabilite in pochi minuti e possono essere gestite direttamente nel sistema storage.
* *Semplicità.* la replica si basa su volumi FlexVol, ovvero container di LUN o file replicati come unico gruppo coerente.
* *Efficienza.* dopo aver stabilito la relazione di replica iniziale, vengono replicate solo le modifiche. Inoltre, funzionalità di efficienza come deduplica e compressione sono preservate, riducendo ulteriormente la quantità di dati da trasferire in un sito remoto.
* *Flessibilità.* i mirror possono essere temporaneamente interrotti per consentire il test delle procedure di ripristino di emergenza, e quindi il mirroring può essere facilmente ristabilito senza la necessità di un rimirroring completo. Solo i dati modificati devono essere applicati per riportare i mirror in sincronizzazione. Il mirroring può anche essere invertito per consentire una rapida risincronizzazione dopo il termine del disastro e il sito originale di nuovo in servizio. Infine, sono disponibili per test e sviluppo cloni in lettura e scrittura dei dati replicati.


ONTAP offre diverse tecnologie di replica, ma la più flessibile è SnapMirror, un'opzione di mirroring asincrono da volume a volume.

Come accennato in precedenza, un volume FlexVol è l'unità di gestione di base per i backup basati su Snapshot e il ripristino basato su SnapRestore. Un volume FlexVol è anche l'unità di base per la replica basata su SnapMirror. Il primo passaggio consiste nel determinare il mirror di base del volume di origine rispetto al volume di destinazione. Dopo l'inizializzazione di questa relazione mirror, tutte le operazioni successive si basano solo sulla replica dei dati modificati.

Dal punto di vista del ripristino, i valori chiave di SnapMirror sono i seguenti:

* Le operazioni di SnapMirror sono semplici da comprendere e possono essere facilmente automatizzate.
* Un semplice aggiornamento di una replica SnapMirror richiede la replica solo delle modifiche delta, riducendo i requisiti di larghezza di banda e consentendo aggiornamenti più frequenti.
* SnapMirror è altamente granulare. Si basa su semplici relazioni da volume a volume, consentendo la creazione di centinaia di repliche e intervalli di replica gestiti in modo indipendente. Non è necessario che la replica sia adatta a ogni scenario.
* La direzione di specchiatura può essere facilmente invertita, pur mantenendo la capacità di aggiornare la relazione in base alle sole modifiche. In questo modo è possibile usufruire di una rapida funzionalità di failback dopo che il sito primario viene ripristinato in servizio dopo un evento disastroso, ad esempio un'interruzione dell'alimentazione. Solo le modifiche devono essere sincronizzate di nuovo all'origine.
* Gli specchi possono essere facilmente rotti e risincronizzati in modo efficiente per consentire la ripetizione delle procedure di ripristino di emergenza.
* SnapMirror in modalità di replica completa a livello di blocco replica non solo i dati di un volume, ma anche gli Snapshot. Questa funzionalità fornisce una copia dei dati e una serie completa di backup sul sito di disaster recovery.


SnapMirror in modalità flessibile della versione consente la replica di snapshot specifiche, consentendo diversi tempi di conservazione nei siti primario e secondario.



== SnapMirror sincrono

SnapMirror Synchronous (SM-S) è una versione avanzata di SnapMirror che offre replica sincrona RPO=0. Viene più spesso utilizzato nelle architetture storage in cui solo il sottoinsieme dei dati totali richiede il mirroring sincrono.

SM-S può operare in due modalità leggermente diverse, Sync e StrictSync.

In modalità di sincronizzazione, le modifiche vengono replicate prima di essere confermate. Questo garantisce un RPO pari a zero, a condizione che la replica sia operativa. Se la modifica non può essere replicata, SM-S può uscire dalla modalità sincrona e consentire il proseguimento delle operazioni. In questo modo è possibile ottenere RPO=0 in circostanze normali, ma i processi dei dati non si interrompono completamente se la destinazione di replica non è disponibile.

StrictSync garantisce un RPO=0. Un errore di replica delle modifiche causa un errore di i/o, che in genere provoca l'arresto dell'applicazione.

Per una spiegazione completa di SM-S, vedere https://www.netapp.com/media/17174-tr4733.pdf?v=1221202075448P["TR-4733"^] E la documentazione ufficiale di ONTAP. Le nuove versioni di ONTAP vengono continuamente aggiunte alle nuove funzioni.



== Gruppi di coerenza

ONTAP consente la creazione di snapshot di gruppi di coerenza; a partire da 9.13.1, ONTAP può replicare gruppi di volumi (ricorda che un volume nella terminologia ONTAP non è una LUN, ma un container di gestione costituito da uno o più file o LUN) come gruppo coerente.

La replica di SnapMirror e l'interruzione della relazione CG SnapMirror preserva la coerenza tra i volumi, mentre SnapMirror Synchronous e SnapMirror Business Continuity preservano la coerenza tra i volumi costituenti.

Il risultato è che è possibile replicare un set di dati multi-volume e assicurare che tutti i volumi siano cross-coerenti. Tra le altre cose, questo consente operazioni di DR "breaking the mirror and go" senza la necessità di fasi aggiuntive di ripristino del database o delle applicazioni.



== MetroCluster e SyncMirror

MetroCluster è anche una soluzione di replica sincrona dedicata a workload mission-critical su larga scala. Replica basata su SyncMirror. Al livello più semplice, SyncMirror crea due set completi di dati con protezione RAID in due posizioni diverse. Potrebbero trovarsi in camere comunicanti all'interno di un data center o a una distanza di molti chilometri.

SyncMirror è completamente integrato con ONTAP e funziona appena al di sopra del livello RAID. Pertanto, tutte le consuete funzionalità di ONTAP, come le copie Snapshot, SnapRestore e NetApp FlexClone, funzionano perfettamente. Il prodotto rimane ONTAP e include un livello aggiuntivo di mirroring sincrono dei dati.

Una raccolta di controller ONTAP che gestiscono i dati SyncMirror viene chiamata configurazione NetApp MetroCluster. Lo scopo principale di MetroCluster è fornire accesso con high Availability ai dati con mirroring sincrono in una varietà di scenari tipici di errore di disaster recovery.

Di seguito sono riportati i valori chiave della protezione dei dati con MetroCluster e SyncMirror:

* Nelle operazioni normali, SyncMirror offre mirroring sincrono garantito tra siti. Un'operazione di scrittura non viene riconosciuta fino a quando non è presente su supporti non volatili in entrambi i siti.
* Se si verifica un guasto nella connettività tra i siti, SyncMirror passa automaticamente alla modalità asincrona per mantenere il sito primario che fornisce dati fino al ripristino della connettività. Una volta ripristinato, garantisce una rapida risincronizzazione aggiornando in modo efficiente le modifiche accumulate sul sito primario. La reinizializzazione completa non è necessaria.


SnapMirror è inoltre completamente compatibile con sistemi basati su SyncMirror. Ad esempio, è possibile che un database primario venga eseguito su un cluster MetroCluster distribuito in due siti geografici. Questo database può anche replicare i backup su un terzo sito come archivi a lungo termine o per la creazione di cloni in un ambiente DevOps.
