---
sidebar: sidebar 
permalink: oracle/oracle-dp-snaprestore.html 
keywords: ontap, snaprestore 
summary: Ripristino rapido del database Oracle tramite snapshot 
searchtitle: Ripristino rapido del database Oracle tramite snapshot 
---
= SnapRestore
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il ripristino rapido dei dati in ONTAP da una Snapshot è fornito dalla tecnologia NetApp SnapRestore, che consente di ripristinare istantaneamente lo stato di un volume AFF o di una LUN ASA.

Quando un set di dati critico non è disponibile, le operazioni di business critiche non sono attive. I nastri possono interrompersi e persino i ripristini da backup basati su disco possono essere lenti da trasferire sulla rete. SnapRestore consente di evitare questi problemi grazie al ripristino quasi istantaneo dei set di dati. Anche i database di diversi petabyte possono essere ripristinati completamente con pochi minuti di lavoro.

Sebbene la tecnologia di base sia la stessa sulle piattaforme AFF e ASA, il loro utilizzo presenta lievi differenze.



== Panoramica AFF

Esistono due forme di SnapRestore su un sistema AFF: basate su file e basate su volumi:

* Singoli file AFF, LUN e namespace e singoli LUN ASA e namespace ASA possono essere ripristinati in pochi secondi, che si tratti di un LUN da 2TB o di un file da 4KB.
* È possibile ripristinare l'intero contenuto di un volume AFF in pochi secondi, indipendentemente dal fatto che si tratti di 10GB o 100TB di dati.


Il motivo per cui SnapRestore funziona in modo così rapido ed efficiente è dovuto alla natura di uno snapshot, che è essenzialmente una vista parallela di sola lettura del contenuto di un volume, LUN o namespace in un preciso momento. I blocchi attivi sono i blocchi reali che possono essere modificati, mentre lo snapshot è una vista di sola lettura dello stato dei blocchi che costituiscono i file e i LUN al momento della creazione dello snapshot.

ONTAP consente solo l'accesso in sola lettura ai dati snapshot, ma i dati possono essere riattivati con SnapRestore. Lo snapshot viene riabilitato come vista di lettura e scrittura dei dati, riportando i dati al loro stato precedente. SnapRestore può operare a livello di volume, file, LUN o namespace. La tecnologia è essenzialmente la stessa con alcune piccole differenze di comportamento.



=== AFF Volume SnapRestore

Il ripristino basato sul volume SnapRestore riporta il contenuto di un intero volume a uno stato precedente. Questa operazione non richiede spostamento dei dati, il che significa che il processo di ripristino è praticamente istantaneo, sebbene l'operazione tramite API o CLI possa richiedere alcuni secondi per essere elaborata. Ripristinare 1GB di dati non è più complicato o dispendioso in termini di tempo rispetto al ripristino di 1PB di dati. Questa funzionalità è il motivo principale per cui molti clienti aziendali migrano ai sistemi storage ONTAP. Offre un RTO misurato in secondi anche per i dataset più grandi.

Uno svantaggio di SnapRestore basato su volumi è causato dal fatto che le modifiche all'interno di un volume sono cumulative nel tempo. Pertanto, ogni snapshot e i dati del file attivo dipendono dalle modifiche che hanno portato a quel punto. Ripristinare uno stato precedente di un volume significa ignorare tutte le modifiche successive apportate ai dati. Ciò che è meno ovvio, tuttavia, è che questo include gli snapshot creati successivamente. Ciò non è sempre desiderabile.

Ad esempio, uno SLA di conservazione dei dati può specificare 30 giorni di backup notturni. Il ripristino di un set di dati in uno snapshot creato cinque giorni fa con Volume SnapRestore scaricherebbe tutti gli snapshot creati nei cinque giorni precedenti, violando lo SLA.

Sono disponibili diverse opzioni per risolvere questo limite:

. I dati possono essere copiati da una snapshot precedente, invece di eseguire un SnapRestore dell'intero volume. Questo metodo funziona meglio con set di dati più piccoli.
. È possibile clonare una snapshot invece di ripristinarla. Il limite a questo approccio è che lo snapshot di origine è una dipendenza del clone. Pertanto, non può essere eliminato a meno che il clone non venga anch'esso eliminato o diviso in un volume indipendente.
. Utilizzo di SnapRestore basati su file.




=== AFF File SnapRestore

Il ripristino basato su file SnapRestore è un processo di ripristino più granulare basato su snapshot, utilizzato con volumi AFF. Anziché ripristinare lo stato di un intero volume, viene ripristinato lo stato di un singolo file, LUN o namespace. Non è necessario eliminare alcuno snapshot, né questa operazione crea alcuna dipendenza da uno snapshot precedente. Il file o il LUN diventano immediatamente disponibili nel volume attivo.

Non è necessario alcuno spostamento dei dati durante un ripristino SnapRestore di un file o di una LUN. Tuttavia, sono necessari alcuni aggiornamenti interni dei metadati per riflettere il fatto che i blocchi sottostanti nei dati ripristinati ora esistono sia in uno snapshot che nel volume attivo. Non dovrebbe esserci alcun effetto sulle prestazioni, ma questo processo blocca la creazione di snapshot fino al suo completamento. La velocità di elaborazione è di circa 5GBps (18TB/ora) in base alla dimensione totale dei file ripristinati.



== Ripristino LUN/namespace ASA

Il ripristino dei dati su ASA è simile a quello AFF SnapRestore. I dati vengono semplicemente ripristinati a uno stato precedente. Il processo è quasi istantaneo e non richiede spostamento dei dati. Presenta inoltre le stesse limitazioni, incluso il requisito che il ripristino di uno snapshot comporti l'eliminazione degli snapshot eliminati successivamente. Se questo rappresenta un problema, esistono due opzioni. La prima consiste nel clonare un LUN/namespace da uno snapshot precedente, lasciando invariato il volume di origine. Si tratta di un processo istantaneo ed efficiente in termini di spazio. In pratica, crea una copia in lettura e scrittura del puntatore ai blocchi presenti nello snapshot. Una seconda opzione è tramite l'API REST, che può utilizzare la stessa logica SnapRestore a file singolo impiegata nei sistemi AFF. Il risultato è un ripristino istantaneo di un LUN/namespace utilizzando i dati di uno snapshot e tutti gli snapshot vengono conservati.
