---
sidebar: sidebar 
permalink: oracle/oracle-dp-consistency-group-backup.html 
keywords: oracle, data, protection, consistency, group, backup, volume, archive, log, redo, controlfiles 
summary: Backup del gruppo di coerenza per i database Oracle su ONTAP 
searchtitle: Backup di gruppi di coerenza dei database Oracle 
---
= Backup di gruppi di coerenza
:allow-uri-read: 


[role="lead"]
Per un backup il più semplice possibile, è sufficiente posizionare l'intero database Oracle in un singolo volume ONTAP, LUN o namespace NVMe.

Proteggere i datafile, i log di archivio, i redo log e i controlfile con un singolo Snapshot è un metodo valido di backup, ripristino e replica. Tuttavia, l'RPO è limitato al point-in-time del backup stesso. È adatto per un RPO di un'ora o superiore. Se un database si estende su volumi AFF o unità di storage ASA, sono necessari gruppi di coerenza utilizzando uno degli strumenti discussi in precedenza.

Ad esempio, l'intero database può risiedere in un singolo volume AFF con la seguente pianificazione degli snapshot:

* 72 snapshot ogni ora
* 30 istantanee notturne
* 12 snapshot mensili


Questo garantisce un RPO di un'ora nel periodo di 72 ore precedenti, oltre a backup notturni e mensili aggiuntivi. È possibile includere più database o file applicativi anche in un singolo volume o in un set di snapshot del gruppo di coerenza per fornire backup coerenti in un ambiente più ampio.
