---
sidebar: sidebar 
permalink: oracle/oracle-asar2-storage-san-config-lun-alignment.html 
keywords: SAN, ASM, LVM, oracle, ASA r2 
summary: Allineamento LUN con database Oracle su ASA r2 
searchtitle: Allineamento LUN per I/O del database Oracle con ASA r2 
---
= Allineamento delle LUN
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'allineamento delle LUN si riferisce all'ottimizzazione dell'i/o in relazione al layout del file system sottostante.

I sistemi ASA r2 utilizzano la stessa architettura ONTAP di AFF/ FAS , ma con un modello di configurazione semplificato. I sistemi ASA r2 utilizzano le Storage Availability Zone (SAZ) anziché gli aggregati, ma i principi di allineamento rimangono gli stessi perché ONTAP gestisce il layout dei blocchi in modo coerente su tutte le piattaforme. Tuttavia, tieni presente questi punti specifici ASA:

* I sistemi ASA r2 forniscono percorsi simmetrici attivi-attivi per tutte le LUN, eliminando i problemi di asimmetria dei percorsi durante l'allineamento.
* Per impostazione predefinita, le unità di archiviazione (LUN) sono sottoposte a thin provisioning; l'allineamento non modifica questo comportamento.
* La riserva di snapshot e l'eliminazione automatica degli snapshot possono essere configurate durante la creazione della LUN (ONTAP 9.18.1 e versioni successive).


Su un sistema ONTAP, lo storage è organizzato in 4KB unità. Un blocco 8KB di un database o di un file system deve corrispondere esattamente a due blocchi 4KB. Se un errore nella configurazione LUN sposta l'allineamento di 1KB:1 in entrambe le direzioni, ogni blocco 8KB esisterebbe su tre blocchi di storage 4KB diversi invece che due. Questa disposizione causerebbe un aumento della latenza e causerebbe l'esecuzione di ulteriori i/o all'interno del sistema di storage.

L'allineamento influisce anche sulle architetture LVM. Se un volume fisico all'interno di un gruppo di volumi logici viene definito sull'intero dispositivo del disco (non vengono create partizioni), il primo blocco 4KB sul LUN si allinea con il primo blocco 4KB sul sistema di storage. Questo è un allineamento corretto. I problemi si verificano con le partizioni perché spostano la posizione iniziale in cui il sistema operativo utilizza il LUN. Finché l'offset viene spostato in intere unità di 4KB, il LUN viene allineato.

Negli ambienti Linux, creare gruppi di volumi logici sull'intero dispositivo di unità. Quando è necessaria una partizione, controllare l'allineamento eseguendo `fdisk -u` e verificando che l'inizio di ogni partizione sia un multiplo di otto. Ciò significa che la partizione inizia da un multiplo di otto settori a 512 byte, ovvero 4KB.

Vedere anche la discussione sull'allineamento dei blocchi di compressione nella sezione link:oracle-ontap-config-efficiency.html["Efficienza"]. Qualsiasi layout allineato ai limiti del blocco di compressione 8KB è allineato ai limiti 4KB.



== Avvertenze di disallineamento

La registrazione di ripristino del database/transazioni genera di solito un i/o non allineato che può causare avvisi fuorvianti riguardo ai LUN disallineati su ONTAP.

La registrazione esegue una scrittura sequenziale del file di registro con scritture di dimensioni variabili. Un'operazione di scrittura del registro che non si allinea ai limiti 4KB non causa normalmente problemi di prestazioni poiché l'operazione di scrittura del registro successiva completa il blocco. Il risultato è che ONTAP è in grado di elaborare quasi tutte le scritture come blocchi da 4KB KB completi, anche se i dati in alcuni blocchi da 4KB KB sono stati scritti in due operazioni separate.

Verificare l'allineamento utilizzando utilità come `sio` O `dd` in grado di generare I/O a una dimensione di blocco definita. Le statistiche di allineamento I/O sul sistema di archiviazione possono essere visualizzate con `stats` comando. Vedere link:../notes/wafl_alignment_verification.html["Verifica dell'allineamento di WAFL"] per maggiori informazioni.

L'allineamento negli ambienti Solaris è più complicato. Fare riferimento a. http://support.netapp.com/documentation/productlibrary/index.html?productID=61343["Configurazione host SAN ONTAP"^] per ulteriori informazioni.

[CAUTION]
====
Negli ambienti Solaris x86, prestare ulteriore attenzione al corretto allineamento poiché la maggior parte delle configurazioni prevede diversi livelli di partizioni. Le sezioni di partizione di Solaris x86 si trovano solitamente in cima a una tabella di partizioni del record di avvio master standard.

====
Ulteriori buone pratiche:

* Verificare il firmware HBA e le impostazioni del sistema operativo rispetto allo strumento NetApp Interoperability Matrix Tool (IMT).
* Utilizzare le utilità sanlun per confermare l'integrità e l'allineamento del percorso.
* Per Oracle ASM e LVM, assicurarsi che i file di configurazione (/etc/lvm/lvm.conf, /etc/sysconfig/oracleasm) siano impostati correttamente per evitare problemi di allineamento.

