---
sidebar: sidebar 
permalink: oracle/oracle-host-config-aix.html 
keywords: oracle, database, ontap, aix, cio 
summary: Database Oracle con AIX 
searchtitle: Database Oracle con IBM AIX 
---
= AIX
:allow-uri-read: 


[role="lead"]
Argomenti di configurazione per database Oracle su IBM AIX con ONTAP.



== I/o simultanei

Per ottenere prestazioni ottimali su IBM AIX è necessario utilizzare l'i/o simultaneo Senza i/o simultaneo, è probabile che le limitazioni delle prestazioni siano dovute al fatto che AIX esegue i/o atomico serializzato, che comporta un overhead significativo.

In origine, NetApp ha consigliato di utilizzare `cio` Opzione di montaggio per forzare l'uso di i/o simultanei sul file system, ma questo processo ha avuto degli inconvenienti e non è più necessario. Dall'introduzione di AIX 5,2 e Oracle 10gR1, Oracle su AIX può aprire singoli file per i/o simultanei, anziché forzare i/o simultanei sull'intero file system.

Il metodo migliore per abilitare l'i/o simultaneo è impostare `init.ora` parametro `filesystemio_options` a. `setall`. In questo modo, Oracle può aprire file specifici da utilizzare con i/o simultanei

Utilizzo di `cio` Come opzione di montaggio, l'utilizzo di i/o simultanei può avere conseguenze negative. Ad esempio, forzando i/o simultanei si disabilita la lettura dei file system, che può danneggiare le prestazioni dell'i/o al di fuori del software del database Oracle, come la copia dei file e l'esecuzione di backup su nastro. Inoltre, prodotti come Oracle GoldenGate e SAP BR*Tools non sono compatibili con l'uso di `cio` Montare l'opzione con alcune versioni di Oracle.

[TIP]
====
*NetApp consiglia* quanto segue:

* Non utilizzare `cio` opzione di montaggio a livello di file system. Abilitare invece l'i/o simultaneo tramite l'utilizzo di `filesystemio_options=setall`.
* Utilizzare solo l' `cio` l'opzione di montaggio dovrebbe essere impostata se non è possibile `filesystemio_options=setall`.


====


== Opzioni di montaggio NFS AIX

Nella tabella seguente sono elencate le opzioni di montaggio NFS AIX per i database Oracle a istanza singola.

|===
| Tipo di file | Opzioni di montaggio 


| Pagina iniziale ADR | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| File di controllo
File di dati
Registri di ripristino | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
intr` 
|===
Nella tabella seguente sono elencate le opzioni di montaggio NFS AIX per RAC.

|===
| Tipo di file | Opzioni di montaggio 


| Pagina iniziale ADR | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| File di controllo
File di dati
Registri di ripristino | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr,noac` 


| `CRS/Voting` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr,noac` 


| Dedicato `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| Condiviso `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr` 
|===
L'aggiunta fa la differenza principale tra le opzioni di montaggio RAC e a istanza singola `noac` alle opzioni di montaggio. Questa aggiunta ha l'effetto di disabilitare la cache del sistema operativo host, consentendo a tutte le istanze nel cluster RAC di avere una visione coerente dello stato dei dati.

Anche se si utilizza il `cio` montare l'opzione e. `init.ora` parametro `filesystemio_options=setall` ha lo stesso effetto di disabilitare la cache dell'host, è comunque necessario utilizzare `noac`. `noac` è obbligatorio per condiviso `ORACLE_HOME` Implementazioni per facilitare la coerenza di file quali file di password Oracle e. `spfile` file di parametri. Se ogni istanza di un cluster RAC dispone di un'istanza dedicata `ORACLE_HOME`, questo parametro non è necessario.



== Opzioni di montaggio di AIX jfs/JFS2

Nella tabella seguente sono elencate le opzioni di montaggio di AIX jfs/JFS2.

|===
| Tipo di file | Opzioni di montaggio 


| Pagina iniziale ADR | Valori predefiniti 


| File di controllo
File di dati
Registri di ripristino | Valori predefiniti 


| ORACLE_HOME | Valori predefiniti 
|===
Prima di utilizzare AIX `hdisk` i dispositivi in qualsiasi ambiente, inclusi i database, controllano il parametro `queue_depth`. Questo parametro non è la profondità della coda HBA, bensì la profondità della coda SCSI dell'individuo `hdisk device. Depending on how the LUNs are configured, the value for `queue_depth` potrebbe essere troppo basso per garantire buone prestazioni. I test hanno dimostrato che il valore ottimale è 64.
