---
sidebar: sidebar 
permalink: mssql/mssql-ag-snapcenter.html 
keywords: MSSQL,SQL Server, data protection, snapmirror, availability group 
summary: Gruppo di disponibilità di Microsoft SQL Server con SnapCenter 
searchtitle: Gruppo di disponibilità di Microsoft SQL Server con SnapCenter 
---
= Gruppo di disponibilità di SQL Server con SnapCenter
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
SnapCenter supporta il backup del database del gruppo di disponibilità SQL Server configurato con il cluster di failover Windows.

Il plugin SnapCenter per Microsoft SQL Server deve essere installato su tutti i nodi del cluster di failover del server Windows. Consultare i link:https://docs.netapp.com/us-en/snapcenter/protect-scsql/concept_prerequisites_for_using_snapcenter_plug_in_for_microsoft_sql_server.html["documentazione"]prerequisiti di ON e la procedura per configurare i plug-in di SnapCenter.

SnapCenter rileva che tutti i database, le istanze e i gruppi di disponibilità negli host e nelle risorse di Windows sono elencati nella pagina delle risorse di SnapCenter.



=== Protezione dei database nel gruppo di disponibilità always-on

I database del gruppo di disponibilità possono essere protetti in più modi.

* Backup a livello di database: Selezionare il database di disponibilità per la pagina delle risorse del database, aggiungere il criterio costituito dal backup completo/registro, pianificare il backup. SnapCenter utilizza il backup indipendentemente dal ruolo del database, sia che si tratti di una replica primaria che di una replica secondaria. La protezione può anche essere configurata aggiungendo database al gruppo di risorse.
* Backup a livello di istanza: Selezionare l'istanza per proteggere tutti i database in esecuzione sull'istanza in base al criterio selezionato. Viene eseguito il backup di tutti i database, incluso il database di disponibilità in esecuzione come replica primaria o secondaria, utilizzando SnapCenter. La protezione può anche essere configurata aggiungendo un'istanza al gruppo di risorse.
* Backup a livello di gruppo di disponibilità: Durante la configurazione del criterio, SnapCenter dispone di un'opzione avanzata per il backup a livello di gruppo di disponibilità. L'impostazione del gruppo di disponibilità nel criterio consente agli utenti di selezionare la preferenza di replica per il backup. È possibile selezionare la replica primaria, secondaria o tutte. L'opzione predefinita si basa sulla replica di backup impostata nella configurazione del gruppo di disponibilità di SQL Server.


L'impostazione del gruppo di disponibilità nel criterio SnapCenter verrà applicata solo se il backup a livello di gruppo di disponibilità viene utilizzato per proteggere i database del gruppo di disponibilità e non viene applicato per il backup a livello di database o istanza.


TIP: *NetApp consiglia* di utilizzare il backup a livello di disponibilità per il backup di tutta la replica in esecuzione sullo storage NetApp ONTAP.



=== Configurazione del backup del registro in SnapCenter

Se il gruppo di disponibilità è impostato su un'installazione autonoma di SQL Server, è necessario montare un disco dedicato su ciascun nodo di un cluster di failover del server Windows. Utilizzare un disco dedicato per configurare la directory del registro per salvare i backup del registro delle transazioni.

Se il gruppo di disponibilità è impostato sul cluster di failover di SQL Server, è necessario creare un disco cluster nell'istanza del cluster di failover di SQL Server per la directory del registro host.



=== Ripristino del database nella configurazione del gruppo di disponibilità con SnapCenter

* SnapCenter fornisce l'opzione di reseeding per ripristinare automaticamente il database dall'ultimo snapshot disponibile nella replica secondaria. L'operazione di risigillatura ripristinerà automaticamente e unirà il backup del database al gruppo di disponibilità.
* Un modo alternativo per ripristinare il database di replica nel gruppo di disponibilità consiste nell'interrompere il gruppo di disponibilità ed eseguire il ripristino completo e completo del registro. Utilizzare SnapCenter per ripristinare il database in modalità norecovery, quindi utilizzare SQL Server Management Studio o T-SQL per accedere nuovamente al gruppo di disponibilità del database.
* Per ripristinare solo il sottoinsieme di dati, è possibile utilizzare le funzionalità di cloning di SnapCenter per creare una copia clone del database. La copia del database viene creata in pochi minuti utilizzando SnapCenter, quindi esportare i dati nella replica primaria utilizzando gli strumenti nativi di SQL Server.


Per le procedure consigliate per configurare il layout dello storage del database in modo da soddisfare i requisiti RTO e RPO, vedere link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714 Best practice per Microsoft SQL Server che utilizza NetApp SnapCenter"].


NOTE: SnapCenter non supporta il gruppo di disponibilità distribuita e il gruppo di disponibilità contenuta.
