---
sidebar: sidebar 
permalink: mssql/mssql-shared-vs-dedicated.html 
keywords: MSSQL,SQL Server, multiple instances, dedicated instance, ONTAP 
summary: Distribuzione delle istanze di Microsoft SQL Server 
---
= Istanza condivisa Microsoft SQL Server rispetto a istanza dedicata
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
È possibile configurare più SQL Server come singola istanza per ogni server o come istanze multiple. La decisione giusta dipende in genere da fattori quali l'utilizzo del server per la produzione o lo sviluppo, indipendentemente dal fatto che l'istanza sia considerata di importanza critica per le operazioni aziendali e gli obiettivi prestazionali.

Le configurazioni delle istanze condivise possono essere inizialmente più semplici da configurare, ma possono causare problemi in cui le risorse vengono divise o bloccate, il che a sua volta causa problemi di prestazioni per altre app che hanno database ospitati nell'istanza condivisa di SQL Server.

La risoluzione dei problemi di prestazioni può essere complicata, perché è necessario capire quale istanza è la causa principale. Questa domanda è valutata rispetto ai costi delle licenze del sistema operativo e delle licenze di SQL Server. Se le performance applicative sono fondamentali, si consiglia vivamente un'istanza dedicata.

Microsoft concede in licenza SQL Server per core a livello di server e non per istanza. Per questo motivo, gli amministratori di database sono tentati di installare tutte le istanze di SQL Server che il server è in grado di gestire per risparmiare sui costi di licenza, il che può portare a gravi problemi di performance in un secondo momento.


TIP: *NetApp consiglia* di scegliere istanze dedicate di SQL Server quando possibile per ottenere prestazioni ottimali.
