---
sidebar: sidebar 
permalink: mssql/mssql-workloads.html 
keywords: MS-SQL,mssql,SQL Server 
summary: Microsoft SQL Server su ONTAP 
---
= Workload di Microsoft SQL Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La piattaforma di database SQL Server supporta molte applicazioni.

Prima di distribuire SQL Server, è necessario comprendere i requisiti del carico di lavoro del database delle applicazioni supportate dalle istanze di SQL Server. Ogni applicazione ha requisiti differenti in termini di capacità, performance e disponibilità, per cui ogni database dovrebbe essere progettato per supportare al meglio tali requisiti. Molte organizzazioni classificano i database in più Tier di gestione, utilizzando i requisiti delle applicazioni per definire gli SLA. I carichi di lavoro di SQL Server possono essere descritti come segue:

* I database OLTP sono spesso anche i database più critici di un'organizzazione. In genere, questi database supportano le applicazioni rivolte ai clienti e sono considerati essenziali per le operazioni chiave dell'azienda. I database OLTP mission-critical e le applicazioni che questi supportano spesso hanno SLA che richiedono elevati livelli di performance e sono sensibili al peggioramento delle performance e alla disponibilità. Potrebbero anche essere candidati per cluster di failover sempre attivi o gruppi di disponibilità sempre attivi. La combinazione di i/o di questi tipi di database è in genere caratterizzata da un tasso di random Read compreso tra il 75% e il 90% e un tasso di scrittura compreso tra il 25% e il 10%.
* I database DSS (Decision Support System) possono anche essere definiti data warehouse. Questi database sono mission-critical in molte organizzazioni che si affidano alle analytics per il loro business. Questi database sono sensibili all'utilizzo della CPU e alle operazioni di lettura dal disco quando vengono eseguite query. In molte organizzazioni, i database DSS sono i più critici durante la fine di mese, trimestre e anno Questo carico di lavoro solitamente presenta una combinazione di i/o di lettura al 100%.




== Analisi comparativa

Il Transaction Process Council (TPC) è una società no profit fondata per definire l'elaborazione delle transazioni e i benchmark dei database e per diffondere al settore dati sulle prestazioni TPC oggettivi e verificabili. I test TPC simulano ambienti di calcolo completi in cui una popolazione di utenti esegue transazioni su database.

[cols="1,1,1"]
|===
| Tipo di carico di lavoro | Scenario | Rapporto lettura/scrittura (percentuali) 


| OLTP | TPC-C | Circa 75/25 MB 


|  | OLTP | TPC-E 


| Circa 90/10 MB |  | DSS 


| TPC-H. | Circa 100/0 MB |  
|===
Sebbene siano disponibili diverse opzioni di generazione di workload, in genere ci dedichiamo alla misurazione delle performance dei database SQL Server nella gestione dei carichi di lavoro transazionali e utilizziamo i tool TPC-e di Microsoft o TPC-H tramite HammerDB (link:http://www.hammerdb.com/document.html["HammerDB.com"]^). Le istruzioni dettagliate su come utilizzare questi benchmark specifici esulano dall'ambito di questo documento.
