---
sidebar: sidebar 
permalink: mssql/mssql-data-protection-ASA.html 
keywords: MSSQL,SQL Server, SnapCenter, data protection, app-consistent backup, ONTAP 
summary: Protezione dei database Microsoft SQL Server su ONTAP con comandi SnapCenter e T-SQL. 
searchtitle: Data Protection di Microsoft SQL Server con il software di gestione NetApp 
---
= Protezione dei dati
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Le strategie di backup dei database devono basarsi su requisiti aziendali identificati, non su capacità teoriche. Combinando la tecnologia Snapshot di ONTAP e sfruttando le API di Microsoft SQL Server, è possibile eseguire rapidamente un backup coerente delle applicazioni indipendentemente dalle dimensioni dei database utente. Per requisiti di gestione dei dati più avanzati o scale-out, NetApp offre SnapCenter.



== SnapCenter

SnapCenter è il software di data Protection di NetApp per le applicazioni aziendali. I database di SQL Server possono essere protetti in modo rapido e semplice con il plug-in SnapCenter per SQL Server e con operazioni del sistema operativo gestite dal plug-in SnapCenter per Microsoft Windows.

L'istanza di SQL Server può essere un'installazione autonoma, un'istanza cluster di failover o può essere un gruppo di disponibilità sempre attivo. Il risultato è che, grazie a un singolo pannello di controllo, i database possono essere protetti, clonati e ripristinati da una copia primaria o secondaria. SnapCenter può gestire database SQL Server sia on-premise, nel cloud che in configurazioni ibride. Le copie dei database possono essere create in pochi minuti sull'host originale o alternativo per lo sviluppo o per il reporting.

SQL Server richiede inoltre un coordinamento tra il sistema operativo e lo storage per garantire che i dati corretti siano presenti negli snapshot al momento della creazione. Nella maggior parte dei casi, l'unico metodo sicuro per eseguire questa operazione è SnapCenter o T-SQL. Gli snapshot creati senza questo coordinamento aggiuntivo potrebbero non essere recuperabili in modo affidabile.

Per ulteriori informazioni sul plug-in di SQL Server per SnapCenter, vedere link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714: Guida alle Best practice per SQL Server con NetApp SnapCenter"^].



== Protezione del database mediante snapshot T-SQL

In SQL Server 2022, Microsoft ha introdotto le istantanee T-SQL che offrono un percorso per la creazione di script e l'automazione delle operazioni di backup. Invece di eseguire copie di dimensioni normali, è possibile preparare il database per le snapshot. Una volta che il database è pronto per il backup, è possibile sfruttare le API REST di ONTAP per creare snapshot.

Di seguito è riportato un esempio di flusso di lavoro di backup:

. Bloccare un database con il comando ALTER. In questo modo il database viene preparato per uno snapshot coerente sullo storage sottostante. Dopo il blocco è possibile scongelare il database e registrare lo snapshot con il comando di BACKUP.
. Eseguire istantanee di più database sulle unità di archiviazione contemporaneamente con il nuovo GRUPPO DI BACKUP e i comandi del SERVER DI BACKUP.
. Se il carico di lavoro del database viene eseguito su più unità di storage, creare gruppi di coerenza per semplificare l'attività di gestione. Il gruppo di coerenza è un insieme di unità di archiviazione gestite come unità singola.
. Eseguire backup COMPLETI o backup COMPLETI COPY_ONLY. Anche questi backup sono registrati in msdb.
. Eseguire il recovery point-in-time utilizzando i backup di log eseguiti con il normale approccio di streaming dopo il backup COMPLETO delle snapshot. Se lo si desidera, sono supportati anche i backup differenziali in streaming.


Per ulteriori informazioni, vedere link:https://learn.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver16["Documentazione Microsoft per conoscere le istantanee T-SQL"^].


TIP: *NetApp recommended* Using SnapCenter to create Snapshot copy. Anche il metodo T-SQL descritto sopra funziona, ma SnapCenter offre un'automazione completa sul processo di backup, ripristino e cloning. Esegue inoltre il rilevamento per garantire che vengano creati gli snapshot corretti.


NOTE: Utilizzare SnapCenter se i database di SQL Server sono ospitati su disco virtuale eseguito in un ambiente virtualizzato VMware. Nel caso in cui i database siano ospitati su server fisici bare metal o su SCSI guest-Connect, eseguire il backup del database utilizzando il comando snapshot T-SQL.
