---
sidebar: sidebar 
permalink: mssql/shared-vs-dedicated.html 
keywords: MS-SQL,mssql,SQL Server 
summary: Microsoft SQL Server su ONTAP 
---
= Istanza condivisa Microsoft SQL Server rispetto a istanza dedicata
:allow-uri-read: 


[role="lead"]
Se un'applicazione dispone di molti schemi e stored procedure, potrebbe influire potenzialmente su altre applicazioni che condividono un'istanza di SQL Server.

Le risorse di istanza potrebbero potenzialmente essere divise o bloccate, il che a sua volta causa problemi di prestazioni per altre app che hanno database ospitati nell'istanza condivisa di SQL Server.

La risoluzione dei problemi di prestazioni può essere complicata, perché è necessario capire quale istanza è la causa principale. Questa domanda è valutata rispetto ai costi delle licenze del sistema operativo e delle licenze di SQL Server. Se le performance applicative sono fondamentali, si consiglia vivamente un'istanza dedicata.

Microsoft concede in licenza SQL Server per core a livello di server e non per istanza. Per questo motivo, gli amministratori di database sono tentati di installare tutte le istanze di SQL Server che il server è in grado di gestire per risparmiare sui costi di licenza, il che può portare a gravi problemi di performance in un secondo momento.


TIP: *NetApp consiglia* di scegliere istanze dedicate di SQL Server quando possibile per ottenere prestazioni ottimali.
