---
sidebar: sidebar 
permalink: oracle/dr/snapmirror/consistency_group_disaster_recovery.html 
keywords: oracle, data protection, DR, CG 
summary: Replica di gruppo di coerenza per i database Oracle 
---
= Disaster recovery di gruppo di coerenza
:allow-uri-read: 


[role="lead"]
La replica di un gruppo di coerenza può essere semplice come la pianificazione della replica di un singolo volume tramite SnapMirror. Sono inclusi file di dati, file di controllo, log di archivio e log di ripristino. Ogni aggiornamento SnapMirror crea una nuova copia del database nel sito di destinazione coerente e pronta per l'attivazione tramite la rottura del mirror.

Se un database deve span volumi, è necessario uno snapshot del gruppo di coerenza (cg-snapshot).

Un ulteriore vantaggio di questa strategia, se utilizzata con SnapMirror in modalità di replica a livello di blocco, è la replica completa di tutti gli snapshot nel sistema di storage di origine. La serie completa di backup viene replicata oltre alla copia di disaster recovery.
