---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-top.html 
keywords: vSphere, datastore, VMFS, FC, NVMe/FC, NVMe/TCP, iSCSI, NFS, vVols 
summary: 'In questa pagina sono descritte le Best practice per l"implementazione di una soluzione di storage ONTAP in un ambiente VMware vSphere.' 
---
= Panoramica delle funzionalità del datastore e del protocollo di vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per collegare VMware vSphere ai datastore su un sistema che esegue ONTAP sono utilizzati sei protocolli:

* FCP
* NVMe/FC
* NVMe/TCP
* ISCSI
* NFS v3
* NFS v4,1


FCP, NVMe/FC, NVMe/TCP e iSCSI sono protocolli a blocchi che utilizzano il VMFS (vSphere Virtual Machine file System) per memorizzare le VM nei LUN di ONTAP o negli namespace NVMe contenuti in un ONTAP FlexVol volume. NFS è un protocollo di file che inserisce le macchine virtuali in datastore (che sono semplicemente volumi ONTAP) senza la necessità di VMFS. SMB (CIFS), iSCSI, NVMe/TCP o NFS possono essere utilizzati anche direttamente da un sistema operativo guest a ONTAP.

Le seguenti tabelle presentano le funzionalità dei datastore tradizionali supportate da vSphere con ONTAP. Queste informazioni non si applicano ai datastore vVols, ma si applicano generalmente a vSphere 6.x e versioni successive che utilizzano versioni ONTAP supportate. È inoltre possibile consultare il link:https://configmax.broadcom.com/guest?vmwareproduct=vSphere&release=vSphere%208.0&categories=2-0["Strumento VMware Configuration Maximums"^] per versioni specifiche di vSphere per confermare i limiti specifici.

|===
| Funzionalità | FC | ISCSI | NVMe-of | NFS 


| Formato | VMFS o RDM (raw device mapping) | VMFS o RDM | VMFS | n/a. 


| Numero massimo di datastore o LUN | 1024 LUNs per host ESXi, fino a 32 percorsi per LUN, fino a 4096 percorsi totali per host, fino a 128 host per datastore | 1024 LUNs per host ESXi, fino a 32 percorsi per LUN, fino a 4096 percorsi totali per host, fino a 128 host per datastore | 256 Namespaces per host ESXi, fino a 32 percorsi per namespace per host, 2048 percorsi totali per host, fino a 16 host per datastore | 256 connessioni NFS per host (interessate da nconnect e trunking di sessione) NFS predefinito. MaxVolumes è 8. Utilizza i tool ONTAP per VMware vSphere per aumentare fino a 256. 


| Dimensione massima datastore | 64 TB | 64 TB | 64 TB | 300 TB di volume FlexVol o superiore con volume FlexGroup 


| Dimensione massima del file del datastore | 62 TB | 62 TB | 62 TB | 62TB con ONTAP 9.12.1P2 e versioni successive 


| Profondità ottimale della coda per LUN o file system | 64-256 | 64-256 | Negoziazione automatica | Fare riferimento a NFS.MaxQueueDefelse in link:vmware-vsphere-settings.html["Host ESXi consigliato e altre impostazioni ONTAP"^]. 
|===
La seguente tabella elenca le funzionalità supportate relative allo storage VMware.

|===
| Capacità/funzionalità | FC | ISCSI | NVMe-of | NFS 


| VMotion | Sì | Sì | Sì | Sì 


| Storage vMotion | Sì | Sì | Sì | Sì 


| VMware ha | Sì | Sì | Sì | Sì 


| SDR (Storage Distributed Resource Scheduler) | Sì | Sì | Sì | Sì 


| Software di backup abilitato per VADP (VMware vStorage APIs for Data Protection) | Sì | Sì | Sì | Sì 


| Microsoft Cluster Service (MSCS) o clustering di failover all'interno di una macchina virtuale | Sì | Sì ^1^ | Sì ^1^ | Non supportato 


| Tolleranza agli errori | Sì | Sì | Sì | Sì 


| Gestione ripristino sito live/ripristino sito | Sì | Sì | No ^2^ | V3 solo ^2^ 


| Macchine virtuali con thin provisioning (dischi virtuali) | Sì | Sì | Sì | Sì
Si tratta dell'impostazione predefinita per tutte le macchine virtuali su NFS quando non si utilizza VAAI. 


| Multipathing nativo di VMware | Sì | Sì | Sì | Il trunking di sessione NFS v4,1 richiede ONTAP 9.14.1 e versioni successive 
|===
La tabella seguente elenca le funzionalità di gestione dello storage ONTAP supportate.

|===
| Funzionalità | FC | ISCSI | NVMe-of | NFS 


| Deduplica dei dati | Risparmi nell'array | Risparmi nell'array | Risparmi nell'array | Risparmi nel datastore 


| Thin provisioning | Datastore o RDM | Datastore o RDM | Datastore | Datastore 


| Ridimensiona datastore | Crescere solo | Crescere solo | Crescere solo | Crescita, crescita automatica e riduzione 


| Plug-in SnapCenter per applicazioni Windows e Linux (in guest) | Sì | Sì | Sì | Sì 


| Monitoraggio e configurazione dell'host con gli strumenti ONTAP per VMware vSphere | Sì | Sì | Sì | Sì 


| Provisioning con gli strumenti ONTAP per VMware vSphere | Sì | Sì | Sì | Sì 
|===
La tabella seguente elenca le funzionalità di backup supportate.

|===
| Funzionalità | FC | ISCSI | NVMe-of | NFS 


| Snapshot ONTAP | Sì | Sì | Sì | Sì 


| SRM supportato da backup replicati | Sì | Sì | No ^2^ | V3 solo ^2^ 


| Volume SnapMirror | Sì | Sì | Sì | Sì 


| Accesso all'immagine VMDK | Software di backup compatibile con SnapCenter e VADP | Software di backup compatibile con SnapCenter e VADP | Software di backup compatibile con SnapCenter e VADP | Software di backup abilitato per SnapCenter e VADP, client vSphere e browser del datastore del client web vSphere 


| Accesso a livello di file VMDK | Software di backup compatibile con SnapCenter e VADP, solo Windows | Software di backup compatibile con SnapCenter e VADP, solo Windows | Software di backup compatibile con SnapCenter e VADP, solo Windows | Software di backup SnapCenter e VADP e applicazioni di terze parti 


| Granularità NDMP | Datastore | Datastore | Datastore | Datastore o macchina virtuale 
|===
^1^ *NetApp recommends* l'utilizzo di iSCSI in-guest per cluster Microsoft anziché VMDK abilitati per multiwriter in un datastore VMFS. Questo approccio è pienamente supportato da Microsoft e VMware, offre grande flessibilità con ONTAP (SnapMirror verso sistemi ONTAP on-premises o nel cloud), è facile da configurare e automatizzare e può essere protetto con SnapCenter. vSphere 7 aggiunge una nuova opzione VMDK in cluster. Questa è diversa dai VMDK abilitati per multiwriter, che richiedono un datastore VMFS 6 con supporto VMDK in cluster abilitato. Si applicano altre restrizioni. Consultare la link:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/setup-for-windows-server-failover-clustering.html["Configurazione per il clustering di failover di Windows Server"^] documentazione di VMware per le linee guida di configurazione.

^2^ i datastore che utilizzano NVMe-of e NFS v4,1 richiedono la replica vSphere. La replica basata su array per NFS v4,1 non è attualmente supportata da SRM. La replica basata su array con NVMe-of non è attualmente supportata dai tool ONTAP per VMware vSphere Storage Replication Adapter (SRA).



== Selezione di un protocollo di storage

I sistemi che eseguono ONTAP supportano tutti i principali protocolli di storage, quindi i clienti possono scegliere ciò che è meglio per il loro ambiente, a seconda dell'infrastruttura di rete esistente e pianificata e delle competenze del personale. Storicamente, i test di NetApp hanno generalmente mostrato poche differenze tra protocolli eseguiti a velocità di linea e numeri di connessioni simili. Tuttavia, NVMe-oF (NVMe/TCP e NVMe/FC) mostra notevoli miglioramenti in IOPS, riduzione della latenza e fino al 50% o più di riduzione del consumo di CPU host da parte dell'IO di storage. All'altro estremo dello spettro, NFS offre la massima flessibilità e facilità di gestione, soprattutto per un numero elevato di VM. Tutti questi protocolli possono essere utilizzati e gestiti con ONTAP tools for VMware vSphere, che fornisce un'interfaccia semplice per creare e gestire i datastore.

I seguenti fattori potrebbero essere utili per valutare una scelta di protocollo:

* *Ambiente operativo corrente.* Sebbene i team IT siano generalmente esperti nella gestione dell'infrastruttura IP Ethernet, non tutti sono esperti nella gestione di un fabric FC SAN. Tuttavia, l'utilizzo di una rete IP generica non progettata per il traffico di storage potrebbe non funzionare bene. Prendi in considerazione l'infrastruttura di rete in uso, gli eventuali miglioramenti pianificati e le competenze e la disponibilità del personale per gestirli.
* *Facilità di configurazione.* oltre alla configurazione iniziale del fabric FC (switch e cablaggio aggiuntivi, zoning e verifica dell'interoperabilità di HBA e firmware), i protocolli a blocchi richiedono anche la creazione e la mappatura di LUN e il rilevamento e la formattazione da parte del sistema operativo guest. Una volta creati ed esportati, i volumi NFS vengono montati dall'host ESXi e pronti all'uso. NFS non dispone di specifiche qualifiche hardware o firmware da gestire.
* *Facilità di gestione.* Con i protocolli SAN, se è necessario più spazio, sono necessari diversi passaggi, tra cui l'espansione di una LUN, una nuova scansione per rilevare le nuove dimensioni e quindi l'espansione del file system. Sebbene sia possibile espandere una LUN, ridurne le dimensioni non lo è. NFS consente un facile aumento o riduzione delle dimensioni, e questo ridimensionamento può essere automatizzato dal sistema storage. SAN offre space reclamation tramite i comandi DEALLOCATE/TRIM/UNMAP del sistema operativo guest, consentendo di restituire all'array lo spazio dei file eliminati. Questo tipo di space reclamation non è possibile con i datastore NFS.
* *Trasparenza dello spazio di storage.* l'utilizzo dello storage è in genere più semplice da visualizzare negli ambienti NFS perché il thin provisioning restituisce immediatamente risparmi. Allo stesso modo, i risparmi di deduplica e clonazione sono immediatamente disponibili per altre macchine virtuali nello stesso datastore o per altri volumi di sistemi storage. La densità delle macchine virtuali è in genere maggiore anche in un datastore NFS, che può migliorare i risparmi della deduplica e ridurre i costi di gestione grazie a un numero inferiore di datastore da gestire.




== Layout del datastore

I sistemi storage ONTAP offrono una grande flessibilità nella creazione di datastore per macchine virtuali e dischi virtuali. Sebbene vengano applicate molte Best practice ONTAP quando si utilizzano gli strumenti ONTAP per il provisioning dei datastore per vSphere (elencati nella sezione link:vmware-vsphere-settings.html["Host ESXi consigliato e altre impostazioni ONTAP"]), di seguito sono riportate alcune linee guida aggiuntive da prendere in considerazione:

* L'implementazione di vSphere con datastore NFS ONTAP si traduce in una soluzione ad alte prestazioni e facile da gestire, che offre rapporti VM-datastore non ottenibili con protocolli di storage a blocchi. Questa architettura può comportare un aumento di dieci volte della densità dei datastore, con una corrispondente riduzione del numero di datastore. Sebbene un datastore più grande possa migliorare l'efficienza dello storage e offrire vantaggi operativi, considera di utilizzare almeno quattro datastore (FlexVol volumi) per nodo per archiviare le VM su un singolo controller ONTAP, al fine di ottenere le massime prestazioni dalle risorse hardware. Questo approccio consente inoltre di stabilire datastore con diverse policy di ripristino. Alcuni possono essere sottoposti a backup o replicati più frequentemente di altri in base alle esigenze aziendali. Non sono necessari più datastore con volumi FlexGroup per le prestazioni, poiché sono scalabili per progettazione.
* *NetApp consiglia* l'uso di volumi FlexVol per la maggior parte dei datastore NFS. A partire da ONTAP 9.8, i volumi FlexGroup sono supportati anche per l'utilizzo come datastore e sono generalmente consigliati per determinati casi d'uso. Altri contenitori di storage ONTAP, come i qtree, non sono generalmente consigliati perché attualmente non sono supportati né dagli ONTAP tools for VMware vSphere né dal plugin NetApp SnapCenter per VMware vSphere.
* Una buona dimensione per un datastore di volumi FlexVol è di circa 4TB - 8TB. Queste dimensioni rappresentano un buon punto di equilibrio per le performance, la facilità di gestione e la protezione dei dati. Inizia in piccolo (ad esempio, 4 TB) e fai crescere il datastore in base alle necessità (fino a un massimo di 300 TB). I datastore più piccoli sono più veloci da ripristinare dal backup o dopo un disastro e possono essere spostati rapidamente nel cluster. Prendere in considerazione l'utilizzo della funzione di dimensionamento automatico di ONTAP per aumentare e ridurre automaticamente il volume in base alle modifiche dello spazio utilizzato. I tool ONTAP per la procedura guidata di provisioning del datastore di VMware vSphere utilizzano il dimensionamento automatico per impostazione predefinita per i nuovi datastore. È possibile personalizzare ulteriormente le soglie di aumento e riduzione e le dimensioni massime e minime con System Manager o la riga di comando.
* In alternativa, i datastore VMFS possono essere configurati con LUN o namespace NVMe (chiamati anche unità storage nei nuovi sistemi ASA) accessibili tramite FC, iSCSI, NVMe/FC o NVMe/TCP. VMFS consente l'accesso simultaneo ai datastore da parte di ogni server ESX in un cluster. Gli archivi di dati VMFS possono avere dimensioni fino a 64 TB e sono costituiti da un massimo di 32 LUN da 2 TB (VMFS 3) o un singolo LUN da 64 TB (VMFS 5). Le dimensioni massime del LUN del ONTAP sono di 128TB GB su sistemi AFF, ASA e FAS. NetApp consiglia sempre di utilizzare una singola LUN di grandi dimensioni per ciascun datastore, invece di provare a utilizzare estensioni. Come per NFS, prendere in considerazione l'utilizzo di datastore multipli (volumi o unità storage) per massimizzare le performance su un singolo controller del ONTAP.
* I sistemi operativi guest precedenti necessitavano di un allineamento con il sistema storage per ottenere le migliori performance ed efficienza dello storage. Tuttavia, i moderni sistemi operativi supportati dai vendor dei distributori Microsoft e Linux come Red Hat non richiedono più modifiche per allineare la partizione del file system con i blocchi del sistema storage sottostante in un ambiente virtuale. Se stai utilizzando un vecchio sistema operativo che potrebbe richiedere un allineamento, cerca nella Knowledge base di supporto NetApp gli articoli che utilizzano "allineamento VM" o richiedi una copia del documento TR-3747 a un contatto commerciale o di un partner NetApp.
* Evitare l'uso di utilità di deframmentazione all'interno del sistema operativo guest, poiché ciò non offre vantaggi in termini di prestazioni e influisce sull'efficienza dello storage e sull'utilizzo dello spazio snapshot. È inoltre consigliabile disattivare l'indicizzazione della ricerca nel sistema operativo guest per i desktop virtuali.
* ONTAP ha guidato il settore con innovative funzionalità di efficienza dello storage, che ti consentono di sfruttare al massimo lo spazio su disco utilizzabile. I sistemi AFF aumentano ulteriormente questa efficienza con la deduplica e la compressione inline predefinite. I dati vengono deduplicati in tutti i volumi in un aggregato, quindi non è più necessario raggruppare sistemi operativi simili e applicazioni simili in un singolo datastore per massimizzare i risparmi.
* In alcuni casi, potrebbe non essere necessario un datastore. Considerare i file system guest-owned come NFS, SMB, NVMe/TCP o iSCSI gestiti dal guest. Per indicazioni specifiche sulle applicazioni, consulta i report tecnici NetApp relativi alla tua applicazione. Ad esempio, link:../oracle/oracle-overview.html["Database Oracle su ONTAP"] ha una sezione sulla virtualizzazione con informazioni utili.
* I dischi di prima classe (o dischi virtuali migliorati) consentono dischi gestiti da vCenter indipendenti da una macchina virtuale con vSphere 6.5 e versioni successive. Anche se gestiti principalmente da API, possono essere utili con vVol, soprattutto se gestiti da OpenStack o Kubernetes tools. Sono supportati da ONTAP e dai tool ONTAP per VMware vSphere.




== Migrazione di datastore e macchine virtuali

Quando si esegue la migrazione delle macchine virtuali da un datastore esistente su un altro sistema storage a ONTAP, è necessario tenere presente alcune procedure:

* Utilizzare Storage vMotion per spostare la maggior parte delle macchine virtuali su ONTAP. Questo approccio non solo non è disgregativo per l'esecuzione di macchine virtuali, ma consente anche funzionalità di efficienza dello storage ONTAP come la deduplica inline e la compressione per elaborare i dati durante la migrazione. Prendere in considerazione l'utilizzo delle funzionalità di vCenter per selezionare più macchine virtuali dall'elenco di inventario e quindi pianificare la migrazione (utilizzare il tasto Ctrl mentre si fa clic su azioni) in un momento appropriato.
* Sebbene sia possibile pianificare attentamente una migrazione verso i datastore di destinazione appropriati, spesso è più semplice migrare in blocco e poi organizzare successivamente secondo necessità. Potresti voler utilizzare questo approccio per guidare la migrazione verso diversi datastore se hai esigenze specifiche di protezione dei dati, come diverse pianificazioni di Snapshot. Inoltre, una volta che le VM sono sul NetApp cluster, lo storage vMotion può utilizzare gli offload VAAI per spostare le VM tra i datastore del cluster senza richiedere una copia basata sull'host. Si noti che NFS non esegue l'offload dello storage vMotion delle VM accese; tuttavia, VMFS lo fa.
* Le macchine virtuali che richiedono una migrazione più accurata includono database e applicazioni che utilizzano lo storage collegato. In generale, considerare l'utilizzo degli strumenti dell'applicazione per gestire la migrazione. Per Oracle, prendere in considerazione l'utilizzo di strumenti Oracle come RMAN o ASM per migrare i file di database. Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-migration-overview.html["Migrazione dei database Oracle sui sistemi di storage ONTAP"^] . Allo stesso modo, per SQL Server, prendere in considerazione l'utilizzo di SQL Server Management Studio o di strumenti NetApp come SnapManager per SQL Server o SnapCenter.




== Strumenti ONTAP per VMware vSphere

La best practice più importante quando si utilizza vSphere con sistemi che eseguono ONTAP è installare e utilizzare il plug-in ONTAP tools for VMware vSphere (precedentemente noto come Virtual Storage Console). Questo plug-in vCenter semplifica la gestione dello storage, migliora la disponibilità e riduce i costi di storage e il sovraccarico operativo, sia che si utilizzi SAN o NAS, su ASA, AFF, FAS o persino ONTAP Select (una versione software-defined di ONTAP in esecuzione su una VM VMware o KVM). Utilizza le best practice per il provisioning dei datastore e ottimizza le impostazioni dell'host ESXi per i timeout multipath e HBA (questi sono descritti nell'Appendice B). Poiché è un plug-in vCenter, è disponibile per tutti i client web vSphere che si connettono al server vCenter.

Il plug-in consente inoltre di utilizzare altri strumenti ONTAP in ambienti vSphere. Il prodotto consente di installare il plug-in NFS per VMware VAAI, che consente l'offload delle copie in ONTAP per le operazioni di cloning delle macchine virtuali, lo space reservation per i file di dischi virtuali con thick provisioning e l'offload delle snapshot ONTAP.


NOTE: Nei cluster vSphere basati su immagini, sarà comunque opportuno aggiungere il NFS Plug-In all'immagine in modo che non vadano fuori conformità quando lo si installa con ONTAP tools.

I tool ONTAP sono anche l'interfaccia di gestione per molte funzioni del provider VASA per ONTAP, supportando una gestione basata su policy di storage con vVol.

In generale, *NetApp consiglia* di utilizzare gli strumenti ONTAP per l'interfaccia di VMware vSphere all'interno di vCenter per effettuare il provisioning dei datastore tradizionali e vVol per assicurarsi che vengano seguite le Best practice.



== Rete generale

La configurazione delle impostazioni di rete quando si utilizza vSphere con sistemi che eseguono ONTAP è semplice e simile ad altre configurazioni di rete. Ecco alcuni aspetti da considerare:

* Separare il traffico di rete dello storage dalle altre reti. È possibile ottenere una rete separata utilizzando una VLAN dedicata o switch separati per lo storage. Se la rete di storage condivide percorsi fisici come gli uplink, potrebbe essere necessario QoS o porte di uplink aggiuntive per garantire una larghezza di banda sufficiente. Non connettere gli host direttamente allo storage; utilizzare gli switch per disporre di percorsi ridondanti e consentire a VMware ha di funzionare senza alcun intervento. Vedere link:vmware-vsphere-network.html["Connessione di rete diretta"] per ulteriori informazioni.
* I frame jumbo possono essere utilizzati se lo si desidera e supportati dalla rete, in particolare quando si utilizza iSCSI. Se vengono utilizzati, assicurarsi che siano configurati in modo identico su tutti i dispositivi di rete, VLAN e così via nel percorso tra lo storage e l'host ESXi. In caso contrario, potrebbero verificarsi problemi di connessione o di prestazioni. La MTU deve essere impostata in modo identico anche sullo switch virtuale ESXi, sulla porta VMkernel e anche sulle porte fisiche o sui gruppi di interfacce di ciascun nodo ONTAP.
* NetApp consiglia di disattivare solo il controllo di flusso di rete sulle porte di cluster Interconnect in un cluster ONTAP. NetApp non fornisce altri consigli sulle Best practice per le restanti porte di rete utilizzate per il traffico dati. Attivare o disattivare secondo necessità. Vedere https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["TR-4182"^] per ulteriori informazioni sul controllo di flusso.
* Quando gli array di storage ESXi e ONTAP sono connessi a reti di storage Ethernet, *NetApp consiglia* di configurare le porte Ethernet a cui questi sistemi si connettono come porte edge Rapid Spanning Tree Protocol (RSTP) o utilizzando la funzione Cisco PortFast. *NetApp consiglia* di abilitare la funzione di trunk PortFast Spanning-Tree in ambienti che utilizzano la funzione PortFast Cisco e che dispongono di trunking VLAN 802,1Q abilitato al server ESXi o agli array di storage ONTAP.
* *NetApp consiglia* le seguenti procedure consigliate per l'aggregazione dei collegamenti:
+
** Utilizzare switch che supportano il link aggregation delle porte su due chassis switch separati utilizzando un approccio di link aggregation multi-chassis, come il Virtual PortChannel (vPC) di Cisco.
** Disattivare LACP per le porte dello switch connesse a ESXi, a meno che non si utilizzi dvSwitch 5.1 o versioni successive con LACP configurato.
** Utilizza LACP per creare aggregati di link per sistemi di storage ONTAP con gruppi di interfacce dinamiche multimode con hash porta o IP. Fare riferimento a. https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html#dynamic-multimode-interface-group["Gestione della rete"^] per ulteriori indicazioni.
** Utilizzare un criterio di raggruppamento hash IP su ESXi quando si utilizza l'aggregazione di collegamenti statici (ad esempio, EtherChannel) e vSwitch standard o l'aggregazione di collegamenti basata su LACP con gli switch distribuiti vSphere. Se non si utilizza l'aggregazione dei collegamenti, utilizzare invece "Route based on the origining virtual port ID" (percorso basato sull'ID della porta virtuale di origine).



