---
sidebar: sidebar 
permalink: vmware/vmware-otv-hardening-login-banner.html 
keywords: VMware, Data protection, security, OTV, Hardening, ONTAP Tools 
summary: Security Hardening Guide for ONTAP tools for VMware vSphere, banner di accesso. 
---
= Banner di accesso di ONTAP Tools 9,13
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il seguente banner di accesso viene visualizzato dopo che l'utente ha immesso un nome utente nel prompt di accesso. Tenere presente che SSH è disattivato per impostazione predefinita e consente l'accesso una tantum solo se attivato dalla console VM.

....
WARNING: Unauthorized access to this system is forbidden and will be
prosecuted by law. By accessing this system, you agree that your actions
may be monitored if unauthorized usage is suspected.
....
Una volta completato l'accesso tramite il canale SSH, viene visualizzato il seguente testo:

 Linux UnifiedVSC 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
....
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
....
....
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
....