---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-overview.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: 'ONTAP è da quasi vent"anni una soluzione di storage leader per gli ambienti VMware vSphere e continua ad aggiungere funzionalità innovative per semplificare la gestione e ridurre i costi. Questo documento presenta la soluzione ONTAP per vSphere, incluse le informazioni più recenti sui prodotti e le Best practice, per ottimizzare l"implementazione, ridurre i rischi e semplificare la gestione.' 
---
= VMware vSphere con ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP è stata una soluzione storage leader per VMware vSphere e, più di recente, per gli ambienti Cloud Foundation dalla sua introduzione nel moderno data center nel 2002. Continua a introdurre funzionalità innovative che semplificano la gestione e riducono i costi.

In questo documento viene presentata la soluzione ONTAP per vSphere, che mette in evidenza le più recenti informazioni sui prodotti e le Best practice per semplificare la distribuzione, ridurre i rischi e semplificare la gestione.


NOTE: Questa documentazione sostituisce i report tecnici precedentemente pubblicati _TR-4597: VMware vSphere for ONTAP_

Le Best practice integrano altri documenti come guide ed elenchi di compatibilità. Sono sviluppati in base a test di laboratorio e a un'ampia esperienza sul campo da parte di tecnici e clienti NetApp. Potrebbero non essere le uniche pratiche supportate che funzionano in ogni ambiente, ma sono generalmente le soluzioni più semplici che soddisfano le esigenze della maggior parte dei clienti.

Questo documento si concentra sulle funzionalità delle versioni recenti di ONTAP (9.x) in esecuzione su vSphere 7,0 o versioni successive. Vedere https://imt.netapp.com/matrix/#search["Tool di matrice di interoperabilità (IMT)"^] e https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san["Guida alla compatibilità VMware"^] per i dettagli relativi a versioni specifiche.
