---
sidebar: sidebar 
permalink: vmware/vmware-srm-deployment_best_practices.html 
keywords: vmware, site, recovery manager, vsrm, svm, layout, segmentation, smt, best, practices, deploy, ontap, tools, vvols, srm, vlsr 
summary: 'Con ONTAP, il concetto di storage virtual machine (SVM) offre una segmentazione rigorosa in ambienti multi-tenant sicuri.' 
---
= Best practice per l'implementazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Nelle sezioni seguenti vengono illustrate le Best practice per la distribuzione con ONTAP e VMware SRM.



== Utilizzare la versione più recente di ONTAP Tools 10

Gli strumenti ONTAP 10 forniscono miglioramenti significativi rispetto alle versioni precedenti, tra cui:

* failover dei test 8x volte più veloce*
* pulizia e protezione 2x volte più veloci*
* failover più veloce del 32%*
* Maggiore scalabilità
* Supporto nativo per layout di siti condivisi


*Questi miglioramenti si basano su test interni e possono variare in base all'ambiente in uso.



== Layout e segmentazione SVM per SMT

Con ONTAP, il concetto di storage virtual machine (SVM) offre una segmentazione rigorosa in ambienti multi-tenant sicuri. Gli utenti SVM su una SVM non possono accedere o gestire le risorse da un'altra. In questo modo, è possibile sfruttare la tecnologia ONTAP creando SVM separate per diverse business unit che gestiscono i propri flussi di lavoro SRM sullo stesso cluster per una maggiore efficienza dello storage globale.

Valutare la possibilità di gestire ONTAP utilizzando account con ambito SVM e LIF di gestione SVM per non solo migliorare i controlli di sicurezza, ma anche le performance. Le performance sono intrinsecamente maggiori quando si utilizzano connessioni con ambito SVM perché l'SRA non è richiesto per elaborare tutte le risorse di un intero cluster, incluse le risorse fisiche. Al contrario, l'IT deve solo comprendere le risorse logiche astratte dalla specifica SVM.



== Best practice per la gestione dei sistemi ONTAP 9

Come indicato in precedenza, è possibile gestire i cluster ONTAP utilizzando credenziali cluster o SVM con ambito e LIF di gestione. Per performance ottimali, puoi prendere in considerazione l'utilizzo delle credenziali con ambito SVM ogni volta che non utilizzi vVol. Tuttavia, in questo modo, è necessario conoscere alcuni requisiti e perdere alcune funzionalità.

* L'account SVM vsadmin predefinito non dispone del livello di accesso richiesto per eseguire le attività degli strumenti ONTAP. Pertanto, devi creare un nuovo account SVM. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-user-role-and-privileges.html["Configurare i ruoli e i privilegi degli utenti ONTAP"] Utilizzando il file JSON incluso. Può essere utilizzato per account SVM o con ambito cluster.
* Poiché il plug-in dell'interfaccia utente vCenter, il provider VASA e il server SRA sono tutti microservizi completamente integrati, devi aggiungere storage all'adattatore SRA in SRM nello stesso modo in cui Aggiungi lo storage nell'interfaccia utente di vCenter per i tool ONTAP. In caso contrario, il server SRA potrebbe non riconoscere le richieste inviate da SRM tramite l'adattatore SRA.
* Il controllo del percorso NFS non viene eseguito quando si utilizzano credenziali con ambito SVM, a meno che non si abbia la precedenza nel gestore dei tool ONTAP e non le si https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["cluster integrati"] associ ai vCenter. Questo perché la posizione fisica è logicamente astratta dalla SVM. Tuttavia, questo non è motivo di preoccupazione, in quanto i sistemi ONTAP moderni non subiscono più alcun calo significativo delle performance quando si utilizzano percorsi indiretti.
* Il risparmio di spazio aggregato dovuto all'efficienza dello storage potrebbe non essere segnalato.
* Se supportati, i mirror di condivisione del carico non possono essere aggiornati.
* La registrazione EMS potrebbe non essere eseguita sui sistemi ONTAP gestiti con credenziali SVM con ambito.

