---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: 'I clienti scelgono con sicurezza ONTAP per vSphere, grazie alle sue soluzioni di storage SAN e NAS unificate e alla nuova architettura dello storage disaggregata semplificata, inclusa nei più recenti array All SAN. Questa piattaforma fornisce un"eccezionale protezione delle snapshot e solidi strumenti di gestione. Trasferendo le funzioni in uno storage dedicato, ONTAP massimizza le risorse host, riduce i costi e mantiene performance ottimali. Inoltre, è possibile eseguire la migrazione dei workload con facilità utilizzando Storage vMotion per VMFS, NFS o vVol.' 
---
= Perché scegliere ONTAP per VMware vSphere?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
I clienti scelgono con fiducia ONTAP per vSphere sia per le soluzioni di storage SAN che NAS.  La nuova architettura di storage disaggregato semplificata, presente negli ultimi All SAN Array, offre un'esperienza semplificata familiare agli amministratori di storage SAN, pur mantenendo la maggior parte delle integrazioni e delle funzionalità dei sistemi ONTAP tradizionali.  I sistemi ONTAP forniscono un'eccezionale protezione snapshot e solidi strumenti di gestione.  Trasferendo le funzioni su un archivio dedicato, ONTAP massimizza le risorse host, riduce i costi e mantiene prestazioni ottimali.  Inoltre, i carichi di lavoro possono essere facilmente migrati tramite Storage vMotion su VMFS, NFS o vVols.



== I vantaggi dell'utilizzo di ONTAP per vSphere

Sono molti i motivi per cui decine di migliaia di clienti hanno scelto ONTAP come soluzione storage per vSphere, ad esempio un sistema storage unificato che supporta protocolli SAN e NAS, solide funzionalità di protezione dei dati che utilizzano snapshot efficienti in termini di spazio e molti strumenti per aiutarti a gestire i dati delle applicazioni. L'utilizzo di un sistema storage separato dall'hypervisor consente di trasferire molte funzioni e massimizzare l'investimento nei sistemi host vSphere. Questo approccio non solo garantisce che le risorse host siano incentrate sui carichi di lavoro delle applicazioni, ma evita anche effetti casuali sulle performance delle applicazioni derivanti dalle operazioni di storage.

L'utilizzo di ONTAP insieme a vSphere è un'ottima combinazione che consente di ridurre le spese per l'hardware host e il software VMware.  Puoi anche proteggere i tuoi dati a un costo inferiore mantenendo prestazioni elevate e costanti.  Poiché i carichi di lavoro virtualizzati sono mobili, è possibile esplorare diversi approcci utilizzando Storage vMotion per spostare le VM tra datastore VMFS, NFS o vVols , tutti sullo stesso sistema di storage.

Ecco i fattori chiave che i clienti apprezzano oggi:

* *Archiviazione unificata.*  I sistemi che eseguono ONTAP sono unificati in diversi modi significativi.  Originariamente, questo approccio si riferiva sia ai protocolli NAS che SAN e ONTAP continua a essere una piattaforma leader per SAN, oltre alla sua forza originaria in NAS.  Nel mondo vSphere, questo approccio potrebbe anche significare un sistema unificato per l'infrastruttura desktop virtuale (VDI) insieme all'infrastruttura server virtuale (VSI).  I sistemi che eseguono ONTAP sono in genere meno costosi per VSI rispetto ai tradizionali array aziendali e tuttavia dispongono di funzionalità avanzate di efficienza di archiviazione per gestire VDI nello stesso sistema.  ONTAP unifica inoltre una varietà di supporti di archiviazione, dagli SSD ai SATA, e può estenderli facilmente al cloud.  Non è necessario acquistare un sistema operativo di archiviazione per le prestazioni, un altro per gli archivi e un altro ancora per il cloud.  ONTAP li collega tutti insieme.
* *All SAN Array (ASA).* I sistemi ONTAP ASA più recenti (a partire dai modelli A1K, A90, A70, A50, A30 e A20) sono costruiti su una nuova architettura dello storage in grado di eliminare il tradizionale paradigma dello storage ONTAP per la gestione degli aggregati e dei volumi. Poiché non ci sono condivisioni di file system, non c'è bisogno di volumi! Tutto lo storage collegato a una coppia ha viene trattato come una SAZ (Storage Availability zone) comune, all'interno della quale i LUN e i namespace NVMe vengono forniti come "Storage Units" (SUS). I più recenti sistemi ASA sono progettati per essere semplici da gestire e con un'esperienza familiare per gli amministratori dello storage SAN. Questa nuova architettura è ideale per gli ambienti vSphere, poiché consente una facile gestione delle risorse storage e fornisce un'esperienza semplificata per gli amministratori dello storage SAN. L'architettura ASA supporta anche la più recente tecnologia NVMe over Fabrics (NVMe-of), che offre performance e scalabilità ancora superiori per i workload vSphere.
* *Tecnologia Snapshot.* ONTAP è stata la prima azienda a offrire la tecnologia Snapshot per la protezione dei dati, che rimane la più avanzata del settore. Questo approccio efficiente in termini di spazio alla data Protection è stato esteso per supportare le API VMware vSphere per l'integrazione degli array (VAAI). Questa integrazione ti consente di sfruttare le funzionalità snapshot di ONTAP per le operazioni di backup e ripristino, riducendo l'impatto sul tuo ambiente di produzione. Questo approccio consente inoltre di utilizzare le snapshot per un rapido recovery delle macchine virtuali, riducendo tempo e lavoro necessari per il ripristino dei dati. Inoltre, la tecnologia snapshot di ONTAP è integrata con le soluzioni VLSR (Live Site Recovery Manager) di VMware, in precedenza Site Recovery Manager [SRM], per fornire una strategia di protezione dei dati completa per il vostro ambiente virtualizzato.
* *Gestione basata su policy di archiviazione e volumi virtuali.*  NetApp è stata uno dei primi partner di progettazione di VMware nello sviluppo di vSphere Virtual Volumes (vVols), fornendo input architettonici e supporto iniziale per vVols e VMware vSphere API for Storage Awareness (VASA).  Questo approccio non solo ha introdotto la gestione granulare dello storage delle VM in VMFS, ma ha anche supportato l'automazione del provisioning dello storage tramite una gestione basata su policy di storage.  Questo approccio consente agli architetti di storage di progettare pool di storage con diverse funzionalità che possono essere facilmente utilizzate dagli amministratori delle VM.  ONTAP è leader nel settore dello storage in termini di scala vVol, supportando centinaia di migliaia di vVols in un singolo cluster, mentre i fornitori di array aziendali e di array flash più piccoli supportano solo alcune migliaia vVols per array.  NetApp sta inoltre guidando l'evoluzione della gestione granulare delle VM con le sue funzionalità future.
* *Efficienza di archiviazione.*  Sebbene NetApp sia stata la prima a fornire la deduplicazione per i carichi di lavoro di produzione, questa innovazione non è stata né la prima né l'ultima in questo settore.  Tutto è iniziato con gli snapshot, un meccanismo di protezione dei dati efficiente in termini di spazio e senza effetti sulle prestazioni, insieme alla tecnologia FlexClone per creare istantaneamente copie di lettura/scrittura delle VM per uso in produzione e backup.  NetApp ha continuato a fornire funzionalità inline, tra cui deduplicazione, compressione e deduplicazione a blocchi zero, per ottenere il massimo spazio di archiviazione dai costosi SSD.  ONTAP ha inoltre aggiunto la possibilità di impacchettare operazioni di I/O e file più piccoli in un blocco di disco utilizzando la compattazione.  La combinazione di queste funzionalità ha portato i clienti a ottenere risparmi fino a 5:1 per VSI e fino a 30:1 per VDI.  La nuova generazione di sistemi ONTAP include anche la compressione e la deduplicazione accelerate dall'hardware, che possono migliorare ulteriormente l'efficienza di archiviazione e ridurre i costi.  Questo approccio consente di archiviare più dati in meno spazio, riducendo il costo complessivo di archiviazione e migliorando le prestazioni.  NetApp è così sicura delle sue capacità di efficienza di storage che offre un collegamento: https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [Garanzia di efficienza^].
* *Multi-tenancy.*  ONTAP è da tempo leader nel multitenancy, consentendo di creare più macchine virtuali di storage (SVM) su un singolo cluster.  Questo approccio consente di isolare i carichi di lavoro e di fornire diversi livelli di servizio a diversi tenant, rendendolo ideale per i fornitori di servizi e le grandi aziende.  L'ultima generazione di sistemi ONTAP include anche il supporto per la gestione della capacità degli inquilini.  Questa funzionalità consente di impostare limiti di capacità per ciascun tenant, assicurando che nessun tenant possa consumare tutte le risorse disponibili.  Questo approccio contribuisce a garantire che tutti gli inquilini ricevano il livello di servizio che si aspettano, garantendo al contempo un elevato livello di sicurezza e isolamento tra gli inquilini.  Inoltre, le funzionalità multi-tenancy di ONTAP sono integrate con la piattaforma vSphere di VMware, consentendo di gestire e monitorare facilmente l'ambiente virtualizzato tramite https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["Strumenti ONTAP per VMware vSphere"] E https://docs.netapp.com/us-en/data-infrastructure-insights/["Informazioni sull'infrastruttura dati"] .
* *Cloud ibrido.*  Che vengano utilizzate per un cloud privato on-premise, un'infrastruttura cloud pubblica o un cloud ibrido che combina il meglio di entrambi, le soluzioni ONTAP ti aiutano a creare il tuo data fabric per semplificare e ottimizzare la gestione dei dati.  Inizia con sistemi all-flash ad alte prestazioni, quindi abbinali a sistemi di archiviazione su disco o cloud per la protezione dei dati e il cloud computing.  Scegli tra Azure, AWS, IBM o Google Cloud per ottimizzare i costi ed evitare vincoli. Sfrutta il supporto avanzato per OpenStack e le tecnologie container in base alle tue esigenze.  NetApp offre inoltre strumenti di backup basati su cloud (SnapMirror Cloud, Cloud Backup Service e Cloud Sync) e di archiviazione e suddivisione in livelli di storage (FabricPool) per ONTAP , per contribuire a ridurre le spese operative e sfruttare l'ampia portata del cloud.
* *E altro ancora.* sfrutta le performance estreme degli array NetApp AFF Serie A per accelerare l'infrastruttura virtualizzata e gestire i costi. Operazioni senza interruzioni, dalla manutenzione agli aggiornamenti fino alla sostituzione completa del sistema storage, utilizzando cluster ONTAP scale-out. Proteggi i dati inattivi con le funzionalità di crittografia NetApp senza costi aggiuntivi. Assicurati che le performance soddisfino i livelli di servizio di business grazie a funzionalità di qualità dei servizi. Fanno tutti parte dell'ampia gamma di funzionalità offerte da ONTAP, il software di Enterprise data management leader del settore.

