---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-sdrs.html 
keywords: Data protection, Space reclamation, VM and datastore cloning, Storage efficiency, thin provisioning, QoS, SIOC, Storage Distributed Resource Scheduler, DRS, Active IQ Unified Manager, Encryption 
summary: 'SnapCenter consente di creare policy di backup che possono essere applicate a più processi. Questi criteri possono definire pianificazione, conservazione, replica e altre funzionalità. Essi consentono una selezione opzionale di snapshot coerenti con le macchine virtuali, che sfrutta la capacità dell"hypervisor di mettere in pausa l"i/o prima di scattare una snapshot VMware.' 
---
= VMware Storage Distributed Resource Scheduler
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Storage Distributed Resource Scheduler (SDR) è una funzione vSphere che posiziona automaticamente le macchine virtuali in un cluster di datastore in base alla latenza di i/o corrente e all'utilizzo dello spazio.

Quindi, sposta le VM o i VMDK senza interruzioni tra gli archivi dati in un cluster di datastore (noto anche come pod), selezionando il migliore datastore in cui posizionare le VM o i VMDK nel cluster di datastore. Un cluster di datastore è un insieme di datastore simili che vengono aggregati in una singola unità di consumo dal punto di vista dell'amministratore di vSphere.

Quando si utilizzano DSP con strumenti ONTAP per VMware vSphere, è necessario prima creare un datastore con il plug-in, utilizzare vCenter per creare il cluster di datastore e quindi aggiungere il datastore. Una volta creato il cluster di datastore, è possibile aggiungere ulteriori datastore al cluster di datastore direttamente dalla procedura guidata di provisioning nella pagina Dettagli.

Altre Best practice ONTAP per I DSP includono:

* Non utilizzare i DSP a meno che non si disponga di un requisito specifico per farlo.
+
** I DSP non sono necessari quando si utilizza ONTAP. GLI SDR non sono consapevoli delle funzionalità di efficienza dello storage ONTAP come la deduplica e la compressione, per cui potrebbero prendere decisioni non ottimali per l'ambiente in uso.
** GLI SDR non sono a conoscenza delle policy QoS di ONTAP, pertanto potrebbero prendere decisioni che non sono ottimali per le performance.
** GLI SDR non sono a conoscenza delle copie snapshot ONTAP, pertanto potrebbero prendere decisioni che causano una crescita esponenziale delle snapshot. Ad esempio, spostando una macchina virtuale in un altro datastore vengono creati nuovi file nel nuovo datastore, con una conseguente crescita dello snapshot. Ciò vale in particolare per le macchine virtuali con dischi di grandi dimensioni o molte istantanee. Quindi, se la macchina virtuale dovesse essere spostata di nuovo nel datastore originale, lo snapshot nel datastore originale crescerà ulteriormente.




Se si utilizzano gli SDR, prendere in considerazione le seguenti procedure consigliate:

* Tutti gli archivi dati del cluster devono utilizzare lo stesso tipo di storage (ad esempio SAS, SATA o SSD), tutti gli archivi dati VMFS o NFS e avere le stesse impostazioni di replica e protezione.
* Considerare l'utilizzo DEGLI SDR in modalità predefinita (manuale). Questo approccio consente di rivedere i suggerimenti e decidere se applicarli o meno. Tenere presente i seguenti effetti delle migrazioni VMDK:
+
** Quando LE SDR spostano i VMDK tra datastore, qualsiasi risparmio di spazio derivante dal cloning o dalla deduplica ONTAP può essere ridotto a seconda della qualità di deduplica o compressione della destinazione.
** Dopo che LE SDR spostano i VMDK, NetApp consiglia di ricreare gli snapshot nel datastore di origine, poiché lo spazio è altrimenti bloccato dalla VM che è stata spostata.
** Lo spostamento di VMDK tra datastore sullo stesso aggregato ha pochi benefici e GLI SDR non hanno visibilità su altri carichi di lavoro che potrebbero condividere l'aggregato.




Ulteriori informazioni sugli SDR sono disponibili nella documentazione VMware all'indirizzo https://knowledge.broadcom.com/external/article/320864/storage-drs-faq.html["Domande frequenti su Storage DRS"^].
