---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-settings.html 
keywords: VMware,vSphere,ESXi,settings,NFS,iSCSI,FC,FCP 
summary: Questo documento categorizza ed enumera le impostazioni di storage e di rete consigliate. 
---
= Host ESXi consigliato e altre impostazioni ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp ha sviluppato una serie di impostazioni ottimali per l'host ESXi sia per protocolli NFS sia per protocolli a blocchi. Sono inoltre fornite indicazioni specifiche per le impostazioni di multipathing e timeout HBA per un corretto comportamento con ONTAP in base ai test interni di NetApp e VMware.

Questi valori sono facilmente impostabili utilizzando gli strumenti ONTAP per VMware vSphere: Dalla pagina di panoramica degli strumenti ONTAP, scorrere fino alla fine e fare clic su Applica impostazioni consigliate nel portlet conformità host ESXi.

Di seguito sono riportate le impostazioni dell'host consigliate per tutte le versioni di ONTAP attualmente supportate.

|===
| *Impostazione host* | *Valore consigliato da NetApp* | *Riavvio richiesto* 


3+| *Configurazione avanzata ESXi* 


| VMFS3.HardwareAcceleratedLocking | Mantieni predefinito (1) | No 


| VMFS3.EnableBlockDelete | Mantenere l'impostazione predefinita (0), ma può essere modificata se necessario. Per ulteriori informazioni, vedere link:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-provisioning-and-space-reclamation-in-vsphere/storage-space-reclamation-in-vsphere/space-reclamation-for-guest-operating-systems.html["Recupero di spazio per VMFS5 macchine virtuali"] | No 


| VMFS3.EnableVMFS6Unmap | Mantenere l'impostazione predefinita (1) per ulteriori informazioni, vedere link:https://www.vmware.com/docs/vmw-vmware-vsphere-apis-array-integration-vaai["API VMware vSphere: Integrazione degli array (VAAI)"] | No 


3+| *Impostazioni NFS* 


| NewSyncInterval | Se non si utilizza vSphere CSI per Kubernetes, impostare come indicato in https://knowledge.broadcom.com/external/article/386364/reducing-excessive-vsan-cnssync-warnings.html["VMware KB 386364"^] | No 


| NET.TcpipelHeapSize | VSphere 6.0 o versione successiva, impostato su 32.
Tutte le altre configurazioni NFS, impostate su 30 | Sì 


| NET.TcpipelHeapMax | Impostato su 512 MB per la maggior parte delle release di vSphere 6.X.
Impostare sul valore predefinito (1024MB) per 6.5U3, 6.7U3 e 7,0 o versioni successive. | Sì 


| NFS.MaxVolumes | VSphere 6,0 o versioni successive, impostare su 256
Tutte le altre configurazioni NFS sono impostate su 64. | No 


| NFS41.MaxVolumes | VSphere 6,0 o versioni successive, impostare su 256. | No 


| NFS.MaxQueueDepth^1^ | VSphere 6.0 o versione successiva, impostato su 128 | Sì 


| NFS.HeartbeatMaxFailures | Impostare su 10 per tutte le configurazioni NFS | No 


| NFS.HeartbeatFrequency | Impostato su 12 per tutte le configurazioni NFS | No 


| NFS.HeartbeatTimeout | Impostare su 5 per tutte le configurazioni NFS. | No 


| SunRPC.MaxConnPerIP | vSphere da 7.0 a 8.0, impostato su 128.  Questa impostazione viene ignorata nelle versioni ESXi successive alla 8.0. | No 


3+| *Impostazioni FC/FCoE* 


| Policy di selezione del percorso | Impostare su RR (round robin) quando si utilizzano percorsi FC con ALUA. Impostare su FISSO per tutte le altre configurazioni.
L'impostazione di questo valore su RR consente di fornire il bilanciamento del carico in tutti i percorsi attivi/ottimizzati.
Il valore FISSO è per le configurazioni precedenti non ALUA e aiuta a prevenire i/o proxy In altre parole, consente di evitare che l'i/o venga collegato all'altro nodo di una coppia ad alta disponibilità (ha) in un ambiente con Data ONTAP in 7-Mode | No 


| Disk.QFullSampleSize | Impostare su 32 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 


| Disk.QFullThreshold | Impostare su 8 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 


| Timeout HBA FC Emulex | Utilizzare il valore predefinito. | No 


| Timeout HBA FC QLogic | Utilizzare il valore predefinito. | No 


3+| *Impostazioni iSCSI* 


| Policy di selezione del percorso | Impostare su RR (round robin) per tutti i percorsi iSCSI.
L'impostazione di questo valore su RR consente di fornire il bilanciamento del carico in tutti i percorsi attivi/ottimizzati. | No 


| Disk.QFullSampleSize | Impostare su 32 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 


| Disk.QFullThreshold | Impostare su 8 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 
|===

NOTE: L'opzione di configurazione avanzata NFS MaxQueueDepth potrebbe non funzionare come previsto quando si utilizzano VMware vSphere ESXi 7.0.1 e VMware vSphere ESXi 7,0.2. Per ulteriori informazioni, fare riferimento link:https://kb.vmware.com/s/article/86331?lang=en_US["Tastiera VMware 86331"]a.

Gli strumenti ONTAP specificano anche alcune impostazioni predefinite durante la creazione di ONTAP FlexVol Volumes e LUN:

|===


| *Strumento ONTAP* | *Impostazione predefinita* 


| Riserva di Snapshot (-percento-spazio-snapshot) | 0 


| Riserva frazionaria (-riserva frazionaria) | 0 


| Access time update (-atime-update) | Falso 


| Readahead minimo (-min-readahead) | Falso 


| Istantanee pianificate | Nessuno 


| Efficienza dello storage | Attivato 


| Garanzia di volume | Nessuno (con thin provisioning) 


| Dimensionamento automatico del volume | grow_shrink 


| Prenotazione di spazio LUN | Disattivato 


| Allocazione dello spazio del LUN | Attivato 
|===


== Impostazioni multipath per performance superiori

Sebbene non sia attualmente configurato dagli strumenti ONTAP disponibili, NetApp suggerisce le seguenti opzioni di configurazione:

* Quando si utilizzano sistemi non ASA in ambienti ad alte prestazioni o quando si testano le prestazioni con un singolo datastore LUN, valutare la possibilità di modificare l'impostazione del bilanciamento del carico della policy di selezione del percorso (PSP) round-robin (VMW_PSP_RR) dall'impostazione IOPS predefinita di 1000 a un valore di 1.  Vederelink:https://knowledge.broadcom.com/external/article?legacyId=2069356["VMware KB 2069356"^] per maggiori informazioni.
* In vSphere 6.7 Update 1, VMware ha introdotto un nuovo meccanismo di bilanciamento del carico di latenza per il Round Robin PSP.  L'opzione di latenza è ora disponibile anche quando si utilizza HPP (High Performance Plugin) con namespace NVMe e con vSphere 8.0u2 e versioni successive, LUN connesse tramite iSCSI e FCP.  La nuova opzione considera la larghezza di banda I/O e la latenza del percorso quando seleziona il percorso ottimale per I/O.  NetApp consiglia di utilizzare l'opzione di latenza in ambienti con connettività di percorso non equivalente, ad esempio nei casi con più hop di rete su un percorso rispetto a un altro, oppure quando si utilizza un sistema NetApp ASA .  Vedere https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/understanding-multipathing-and-failover-in-the-esxi-environment/viewing-and-managing-storage-paths-on-esxi-hosts.html#GUID-1940AE9E-04CF-40BE-BB71-398621F0642E-en["Modifica dei parametri predefiniti per la latenza Round Robin"^] per maggiori informazioni.




== Documentazione aggiuntiva

Per FCP e iSCSI con vSphere 7, è possibile trovare ulteriori dettagli all'indirizzo link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_7.html["Utilizzo di VMware vSphere 7.x con ONTAP"^] per FCP e iSCSI con vSphere 8. Per ulteriori dettagli, visitare la pagina link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["Utilizzo di VMware vSphere 8.x con ONTAP"^] relativa a NVMe-of con vSphere 7. Per ulteriori dettagli, visitare il sito link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_7.html["Per NVMe-of, ulteriori dettagli sono disponibili nella pagina NVMe-of host Configuration per ESXi 7.x con ONTAP"^] per NVMe-of con vSphere 8, ulteriori dettagli sono disponibili all'indirizzo link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Per NVMe-of, ulteriori dettagli sono disponibili nella pagina NVMe-of host Configuration per ESXi 8.x con ONTAP"^]
