---
sidebar: sidebar 
permalink: vmware/vmware-srm-ontap-tools-features.html 
keywords: vmware, site, recovery manager, vsrm, vsphere, ipv6, support, rest, api, replication, ccols, spbm, srm, appliance based 
summary: Funzioni, limiti e vVol supportano con gli strumenti ONTAP. 
---
= Nuove funzioni con gli strumenti VLSR/SRM e ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Con la transizione dall'appliance virtuale legacy, gli strumenti ONTAP offrono una vasta gamma di nuove funzionalità, limiti più elevati e nuovo supporto vVol.



== Ultime versioni di vSphere e Site Recovery Manager

NetApp ha condiviso una partnership profonda con VMware da quasi vent'anni e si impegna a fornire il supporto per le ultime release il più presto possibile. Controllare sempre l'NetApp https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Tool di matrice di interoperabilità (IMT)"^] per le più recenti combinazioni di software qualificate.



== Supporto per IPv6

IPv6 è ora supportato con le seguenti limitazioni:

* Non supportato con SRM 8.2 (8.1, 8.3 e 8. sono supportati 4 e versioni successive)
* Controllare la https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Tool di matrice di interoperabilità (IMT)"^] per le ultime versioni qualificate.




== Maggiore scalabilità

Gli strumenti ONTAP 10,4 SRA sono ora in grado di supportare la massima scala di VLSR/SRM.

* Numero totale di VM protette = 5000
* Numero di VM per gruppo di protezione = 1000
* Numero totale di piani di recupero = 250
* Numero totale di gruppi di protezione per piano di ripristino = 250
* Numero totale di datastore replicati = 255
* Numero totale di piani di ripristino in esecuzione simultanea. = 10




== Replica sincrona

Una nuova funzionalità attesa da tempo e molto attesa è SnapMirror Synchronous (SM-S) con ONTAP 9.5 e versioni successive, che offre una soluzione di replica dei dati zero RPO granulare per le applicazioni mission-critical. SM-S richiede gli strumenti ONTAP 9.8 o versioni successive.



== Supporto API REST

La configurazione del server SRA può ora essere gestita dalle API REST. È stata aggiunta un'interfaccia utente Swagger per facilitare la creazione dei flussi di lavoro di automazione e può essere trovata sull'appliance ONTAP Tools all'indirizzo `https://<appliance>:8443/`.
