---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: 'La soluzione ONTAP per VMware Live Site Recovery (VLSR) e Site Recovery Manager (SRM)' 
---
= VMware Live Site Recovery con ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP è una soluzione di storage leader per VMware vSphere e, più di recente, per Cloud Foundation, da quando ESX è stato introdotto nei data center moderni più di due decenni fa.  NetApp continua a introdurre sistemi innovativi, come l'ultima generazione della serie ASA A, insieme a funzionalità come la sincronizzazione attiva SnapMirror .  Questi progressi semplificano la gestione, migliorano la resilienza e riducono il costo totale di proprietà (TCO) della tua infrastruttura IT.

Questo documento presenta la soluzione ONTAP per VMware Live Site Recovery (VLSR), precedentemente nota come Site Recovery Manager (SRM), il software di disaster recovery (DR) leader del settore di VMware, comprese le informazioni più recenti sul prodotto e le best practice per semplificare la distribuzione, ridurre i rischi e semplificare la gestione continua.


NOTE: Questa documentazione sostituisce il rapporto tecnico precedentemente pubblicato _TR-4900: VMware Site Recovery Manager con ONTAP_

Le Best practice integrano altri documenti come guide e strumenti di compatibilità. Sono sviluppati in base a test di laboratorio e a un'ampia esperienza sul campo da parte di tecnici e clienti NetApp. In alcuni casi, le Best practice consigliate potrebbero non essere adatte al tuo ambiente; tuttavia, sono generalmente le soluzioni più semplici che soddisfano le esigenze della maggior parte dei clienti.

Questo documento si concentra sulle funzionalità delle versioni recenti di ONTAP 9 utilizzate insieme agli strumenti ONTAP per VMware vSphere 10,4 (che include l'adattatore di replica dello storage NetApp [SRA] e il provider VASA [VP]), nonché su VMware Live Site Recovery 9.



== Perché utilizzare ONTAP con VLSR o SRM?

Le piattaforme di gestione dati NetApp basate su ONTAP sono tra le soluzioni di storage più ampiamente adottate per VLSR.  Le ragioni sono molteplici: una piattaforma di gestione dei dati sicura, ad alte prestazioni e con protocollo unificato (NAS e SAN insieme) che fornisce efficienza di archiviazione senza pari nel settore, multi-tenancy, controlli della qualità del servizio, protezione dei dati con snapshot efficienti in termini di spazio e replica con SnapMirror.  Tutto ciò sfrutta l'integrazione nativa multi-cloud ibrida per la protezione dei carichi di lavoro VMware e una miriade di strumenti di automazione e orchestrazione a portata di mano.

Quando si utilizza SnapMirror per la replica basata su array, si sfrutta una delle tecnologie più collaudate e mature di ONTAP.  SnapMirror offre il vantaggio di trasferimenti di dati sicuri e altamente efficienti, copiando solo i blocchi del file system modificati e non intere VM o datastore.  Anche questi blocchi sfruttano il risparmio di spazio, tramite deduplicazione, compressione e compattazione.  I moderni sistemi ONTAP ora utilizzano SnapMirror indipendente dalla versione, consentendo flessibilità nella selezione dei cluster di origine e di destinazione.  SnapMirror è diventato davvero uno degli strumenti più potenti disponibili per il disaster recovery.

Indipendentemente dal fatto che si utilizzino datastore tradizionali collegati a NFS, iSCSI o Fibre Channel (ora con supporto per datastore vVols ), VLSR fornisce un'offerta proprietaria affidabile che sfrutta il meglio delle funzionalità ONTAP per il disaster recovery o la pianificazione e l'orchestrazione della migrazione del data center.



== In che modo VLSR sfrutta ONTAP 9

VLSR sfrutta le tecnologie avanzate di gestione dei dati dei sistemi ONTAP integrandosi con i tool ONTAP per VMware vSphere, un'appliance virtuale che include tre componenti principali:

* Il plug-in vCenter dei tool ONTAP, in precedenza noto come Virtual Storage Console (VSC), semplifica le funzionalità di gestione ed efficienza dello storage, aumenta la disponibilità e riduce i costi dello storage e l'overhead operativo, sia che si stia utilizzando SAN o NAS. Utilizza le Best practice per il provisioning degli archivi dati e ottimizza le impostazioni degli host ESXi per gli ambienti di storage a blocchi e NFS. Per tutti questi vantaggi, NetApp consiglia questo plug-in quando si utilizza vSphere con sistemi che eseguono ONTAP.
* Il ONTAP provider VASA supporta le API vStorage di VMware per il framework VASA (Storage Awareness). IL provider VASA connette vCenter Server a ONTAP per facilitare il provisioning e il monitoraggio dello storage delle macchine virtuali. In questo modo, è stato abilitato il supporto dei volumi virtuali VMware (vVol) e la gestione delle policy storage delle macchine virtuali e delle performance dei singoli vVol delle macchine virtuali. Fornisce inoltre allarmi per il monitoraggio della capacità e della conformità con i profili.
* SRA viene utilizzato insieme a VLSR per gestire la replica dei dati delle macchine virtuali tra siti di produzione e disaster recovery per datastore VMFS e NFS tradizionali e per il test senza interruzioni delle repliche DR. Consente di automatizzare le attività di rilevamento, ripristino e protezione. Include sia un server appliance SRA che adattatori SRA per il server Windows SRM e l'appliance VLSR.


Dopo aver installato e configurato gli adattatori SRA sul server VLSR per la protezione dei datastore non vVols, è possibile iniziare l'attività di configurazione dell'ambiente vSphere per il disaster recovery.

SRA fornisce un'interfaccia di comando e controllo per il server VLSR per la gestione dei volumi ONTAP FlexVol che contengono le macchine virtuali (VM) VMware, nonché la replica SnapMirror che le protegge.

VLSR può testare il tuo piano DR in modo non invasivo utilizzando la tecnologia proprietaria FlexClone di NetApp per creare cloni quasi istantanei dei tuoi datastore protetti nel tuo sito DR.  VLSR crea un sandbox per effettuare test in modo sicuro, in modo che la tua organizzazione e i tuoi clienti siano protetti in caso di un vero disastro, dandoti fiducia nella capacità della tua organizzazione di eseguire un failover durante un disastro.

In caso di disastro reale o persino di migrazione pianificata, VLSR consente di inviare eventuali modifiche dell'ultimo minuto al dataset tramite un aggiornamento finale di SnapMirror (se si sceglie di farlo). Quindi, interrompe il mirror e monta il datastore sugli host DR. A questo punto, le VM possono essere alimentate automaticamente in qualsiasi ordine in base alla strategia prepianificata.


NOTE: Mentre i sistemi ONTAP permettono di accoppiare le SVM nello stesso cluster per la replica SnapMirror, questo scenario non viene testato e certificato con VLSR. Pertanto, si consiglia di utilizzare solo SVM di cluster diversi quando si utilizza VLSR.



== VLSR con ONTAP e altri casi di utilizzo: Cloud ibrido e migrazione

L'integrazione della distribuzione VLSR con le funzionalità avanzate di gestione dei dati ONTAP consente di ottenere prestazioni e scalabilità notevolmente migliorate rispetto alle opzioni di archiviazione locale.  Ma più di questo, offre la flessibilità del cloud ibrido.  Il cloud ibrido consente di risparmiare denaro suddividendo i blocchi di dati inutilizzati dal tuo array ad alte prestazioni al tuo hyperscaler preferito tramite FabricPool, che potrebbe essere un archivio S3 locale come NetApp StorageGRID.  È inoltre possibile utilizzare SnapMirror per sistemi edge-based con ONTAP Select definito dal software o DR basato su cloud utilizzando Cloud Volumes ONTAP (CVO) o https://www.equinix.com/partners/netapp["Storage NetApp su Equinix Metal®"^] o altri servizi ONTAP ospitati.

Quindi, grazie a FlexClone, è possibile eseguire un failover di test nel data center di un cloud service provider con un impatto dello storage prossimo allo zero. Proteggere la tua organizzazione può ora costare meno che mai.

VLSR può anche essere utilizzato per eseguire migrazioni pianificate sfruttando SnapMirror per trasferire in modo efficiente le macchine virtuali da un data center all'altro o anche all'interno dello stesso data center, sia esso il tuo, o tramite un numero qualsiasi di partner service provider NetApp.
