---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-flexgroups.html 
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe/FC, iSCSI, NFS, vVols 
summary: 'Questa pagina descrive le Best practice per l"implementazione di una soluzione di storage NetApp ONTAP in un ambiente VMware vSphere.' 
---
= Gruppi flessibili
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revnumber: 9.8 adds support for FlexGroup datastores in vSphere
:revdate: along with the ONTAP tools for VMware vSphere 9.8 release.


FlexGroup semplifica la creazione di datastore di grandi dimensioni e crea automaticamente una serie di volumi costituenti per ottenere le massime performance da un sistema ONTAP. Utilizza FlexGroup con vSphere per un singolo datastore vSphere scalabile con la potenza di un cluster ONTAP completo.

Oltre ai test di sistema estesi con carichi di lavoro vSphere, ONTAP 9.8 aggiunge anche un nuovo meccanismo di offload delle copie per gli archivi dati FlexGroup. Questo utilizza un motore di copia migliorato per copiare i file tra i componenti in background, consentendo l'accesso sia all'origine che alla destinazione. Copie multiple utilizzano cloni di file immediatamente disponibili ed efficienti in termini di spazio all'interno di un costituente, se necessario, in base alla scala.

ONTAP 9.8 aggiunge inoltre nuove metriche delle performance basate su file (IOPS, throughput e latenza) per i file FlexGroup, che possono essere visualizzate nei report del dashboard e delle macchine virtuali di ONTAP Tools. Il plug-in ONTAP Tools per VMware vSphere consente inoltre di impostare le regole di qualità del servizio (QoS) utilizzando una combinazione di IOPS massimo e/o minimo. Questi possono essere impostati su tutte le macchine virtuali in un datastore o singolarmente per macchine virtuali specifiche.

Ecco alcune Best practice aggiuntive sviluppate da NetApp:

* Utilizza le impostazioni predefinite di provisioning FlexGroup. Mentre i tool ONTAP per VMware vSphere sono consigliati perché creano e montano il FlexGroup all'interno di vSphere, è possibile utilizzare Gestione di sistema ONTAP o la riga di comando per esigenze speciali. Anche in questo caso, utilizza le impostazioni predefinite, ad esempio il numero di membri costitutivi per nodo, perché questo è ciò che è stato testato con vSphere.
* Quando si ridimensiona un datastore FlexGroup, tenere presente che FlexGroup è costituito da più volumi FlexVol più piccoli che creano uno spazio dei nomi più grande. Di conseguenza, dimensionare l'archivio dati in modo che sia almeno 8 volte più grande della macchina virtuale più grande. Ad esempio, se nell'ambiente si dispone di una macchina virtuale da 6 TB, dimensionare il datastore FlexGroup non inferiore a 48 TB.
* Consentire a FlexGroup di gestire lo spazio del datastore. Il dimensionamento automatico e il dimensionamento elastico sono stati testati con datastore vSphere. Nel caso in cui il datastore si avvicini alla capacità massima, utilizzare i tool ONTAP per VMware vSphere o un altro tool per ridimensionare il volume FlexGroup. FlexGroup mantiene la capacità e gli inode bilanciati tra i componenti, assegnando la priorità ai file all'interno di una cartella (VM) sullo stesso costituente, se la capacità lo consente.
* VMware e NetApp attualmente non supportano un approccio di rete multipath comune. Per NFSv4.1, NetApp supporta pNFS, mentre VMware supporta il trunking di sessione. NFSv3 non supporta percorsi fisici multipli per un volume. Per FlexGroup con ONTAP 9.8, la Best practice consigliata consiste nel consentire ai tool ONTAP per VMware vSphere di eseguire il montaggio singolo, poiché l'effetto dell'accesso indiretto è generalmente minimo (microsecondi). È possibile utilizzare il DNS round-robin per distribuire gli host ESXi attraverso le LIF su nodi diversi in FlexGroup, ma ciò richiederebbe la creazione e il montaggio di FlexGroup senza strumenti ONTAP per VMware vSphere. Le funzionalità di gestione delle performance non sarebbero quindi disponibili.
* Il supporto del datastore FlexGroup vSphere è stato testato fino a 1500 macchine virtuali con la release 9.8.
* Utilizzare il plug-in NFS per VMware VAAI per l'offload delle copie. Si noti che, sebbene il cloning sia migliorato all'interno di un datastore FlexGroup, ONTAP non offre vantaggi significativi in termini di performance rispetto alla copia host ESXi durante la copia di macchine virtuali tra volumi FlexVol e/o FlexGroup.
* Utilizza gli strumenti ONTAP per VMware vSphere 9.8 per monitorare le performance delle macchine virtuali FlexGroup utilizzando metriche ONTAP (report dashboard e macchine virtuali) e per gestire la qualità del servizio su singole macchine virtuali. Queste metriche non sono attualmente disponibili tramite i comandi o le API ONTAP.
* QoS (IOPS max/min) può essere impostato su singole macchine virtuali o su tutte le macchine virtuali in un datastore in quel momento. L'impostazione della QoS su tutte le macchine virtuali sostituisce le impostazioni separate per ogni macchina virtuale. Le impostazioni non si estendono alle macchine virtuali nuove o migrate in futuro; impostare la QoS sulle nuove macchine virtuali o riapplicare la QoS a tutte le macchine virtuali nel datastore.
* Il plug-in SnapCenter per VMware vSphere release 4.4 supporta il backup e il ripristino delle macchine virtuali in un datastore FlexGroup sul sistema di storage primario. Mentre SnapMirror può essere utilizzato manualmente per replicare un FlexGroup su un sistema secondario, SCV 4.4 non gestisce le copie secondarie.

