---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: 'I clienti scelgono con sicurezza ONTAP per vSphere, grazie alle sue soluzioni di storage SAN e NAS unificate e alla nuova architettura dello storage disaggregata semplificata, inclusa nei più recenti array All SAN. Questa piattaforma fornisce un"eccezionale protezione delle snapshot e solidi strumenti di gestione. Trasferendo le funzioni in uno storage dedicato, ONTAP massimizza le risorse host, riduce i costi e mantiene performance ottimali. Inoltre, è possibile eseguire la migrazione dei workload con facilità utilizzando Storage vMotion per VMFS, NFS o vVol.' 
---
= Perché scegliere ONTAP per VMware vSphere?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
I clienti scelgono con fiducia ONTAP per vSphere sia per le soluzioni storage SAN che per quelle NAS. La nuova architettura dello storage disaggregata semplificata, inclusa nella versione più recente degli array All SAN, offre un'esperienza semplificata che familiare agli amministratori dello storage SAN, mantenendo al contempo la maggior parte delle integrazioni e del set di funzionalità dei sistemi ONTAP tradizionali. I sistemi ONTAP offrono un'eccezionale protezione delle snapshot e solidi tool di gestione. Trasferendo le funzioni in uno storage dedicato, ONTAP massimizza le risorse host, riduce i costi e mantiene performance ottimali. Inoltre, è possibile eseguire la migrazione dei workload con facilità utilizzando Storage vMotion per VMFS, NFS o vVol.



== I vantaggi dell'utilizzo di ONTAP per vSphere

Sono molti i motivi per cui decine di migliaia di clienti hanno scelto ONTAP come soluzione storage per vSphere, ad esempio un sistema storage unificato che supporta protocolli SAN e NAS, solide funzionalità di protezione dei dati che utilizzano snapshot efficienti in termini di spazio e molti strumenti per aiutarti a gestire i dati delle applicazioni. L'utilizzo di un sistema storage separato dall'hypervisor consente di trasferire molte funzioni e massimizzare l'investimento nei sistemi host vSphere. Questo approccio non solo garantisce che le risorse host siano incentrate sui carichi di lavoro delle applicazioni, ma evita anche effetti casuali sulle performance delle applicazioni derivanti dalle operazioni di storage.

L'utilizzo di ONTAP insieme a vSphere è un'ottima combinazione che consente di ridurre le spese relative all'hardware host e al software VMware. Puoi anche proteggere i tuoi dati a un costo inferiore con performance elevate e costanti. Poiché i carichi di lavoro virtualizzati sono mobili, è possibile esplorare diversi approcci utilizzando Storage vMotion per spostare le macchine virtuali tra datastore VMFS, NFS o vVol, tutti sullo stesso sistema storage.

Ecco i fattori chiave che i clienti apprezzano oggi:

* *Archiviazione unificata.* I sistemi che eseguono ONTAP sono unificati in diversi modi significativi. In origine, questo approccio si riferiva ai protocolli NAS e SAN e ONTAP continua a essere una piattaforma leader per SAN insieme alla sua forza originale nel NAS. Nel mondo vSphere, questo approccio potrebbe anche significare un sistema unificato per l'infrastruttura di desktop virtuale (VDI) insieme all'infrastruttura di server virtuale (VSI). I sistemi che eseguono ONTAP sono di solito meno costosi per VSI rispetto agli array aziendali tradizionali e allo stesso tempo dispongono di funzionalità avanzate per l'efficienza dello storage per gestire l'infrastruttura di desktop virtuale nello stesso sistema. ONTAP unifica inoltre una vasta gamma di supporti storage, da SSD a SATA, e può estenderli facilmente nel cloud. Non è necessario acquistare un sistema operativo per lo storage per le performance, un altro per gli archivi e un altro ancora per il cloud. ONTAP li lega tutti insieme.
* *All SAN Array (ASA).* I sistemi ONTAP ASA più recenti (a partire dai modelli A1K, A90, A70, A50, A30 e A20) sono costruiti su una nuova architettura dello storage in grado di eliminare il tradizionale paradigma dello storage ONTAP per la gestione degli aggregati e dei volumi. Poiché non ci sono condivisioni di file system, non c'è bisogno di volumi! Tutto lo storage collegato a una coppia ha viene trattato come una SAZ (Storage Availability zone) comune, all'interno della quale i LUN e i namespace NVMe vengono forniti come "Storage Units" (SUS). I più recenti sistemi ASA sono progettati per essere semplici da gestire e con un'esperienza familiare per gli amministratori dello storage SAN. Questa nuova architettura è ideale per gli ambienti vSphere, poiché consente una facile gestione delle risorse storage e fornisce un'esperienza semplificata per gli amministratori dello storage SAN. L'architettura ASA supporta anche la più recente tecnologia NVMe over Fabrics (NVMe-of), che offre performance e scalabilità ancora superiori per i workload vSphere.
* *Tecnologia Snapshot.* ONTAP è stata la prima azienda a offrire la tecnologia Snapshot per la protezione dei dati, che rimane la più avanzata del settore. Questo approccio efficiente in termini di spazio alla data Protection è stato esteso per supportare le API VMware vSphere per l'integrazione degli array (VAAI). Questa integrazione ti consente di sfruttare le funzionalità snapshot di ONTAP per le operazioni di backup e ripristino, riducendo l'impatto sul tuo ambiente di produzione. Questo approccio consente inoltre di utilizzare le snapshot per un rapido recovery delle macchine virtuali, riducendo tempo e lavoro necessari per il ripristino dei dati. Inoltre, la tecnologia snapshot di ONTAP è integrata con le soluzioni VLSR (Live Site Recovery Manager) di VMware, in precedenza Site Recovery Manager [SRM], per fornire una strategia di protezione dei dati completa per il vostro ambiente virtualizzato.
* *Gestione basata su volumi virtuali e criteri di archiviazione.* NetApp è stato un primo partner di progettazione di VMware nello sviluppo di vVol (vSphere Virtual Volumes), fornendo input architetturale e supporto iniziale per vVol e API VMware vSphere per la consapevolezza dello storage (VASA). Questo approccio non solo ha portato a VMFS una gestione granulare dello storage delle macchine virtuali, ma ha anche supportato l'automazione del provisioning dello storage tramite la gestione basata su criteri dello storage. Questo approccio consente agli architetti dello storage di progettare pool di storage con diverse funzionalità che possono essere facilmente utilizzate dagli amministratori delle macchine virtuali. ONTAP è leader nel settore dello storage in termini di scalabilità vVol, supportando centinaia di migliaia di vVol in un singolo cluster, mentre i vendor di array Enterprise e flash array più piccoli supportano solo diverse migliaia di vVol per array. NetApp sta inoltre guidando l'evoluzione della gestione granulare delle macchine virtuali con le capacità imminenti.
* *Efficienza dello storage.* Anche se NetApp è stato il primo a fornire la deduplica per carichi di lavoro di produzione, questa innovazione non è stata la prima o l'ultima in questo campo. Il prodotto è partito dalle snapshot, un meccanismo di protezione dei dati efficiente in termini di spazio, senza effetti sulle performance, e dalla tecnologia FlexClone per creare istantaneamente copie in lettura/scrittura delle macchine virtuali per l'utilizzo in produzione e nel backup. NetApp ha continuato a offrire funzionalità inline, tra cui deduplica, compressione e deduplica a blocchi zero, per eliminare il maggior numero di storage dai costosi SSD. ONTAP ha inoltre aggiunto la possibilità di inserire file e operazioni di i/o di dimensioni minori in un blocco di dischi utilizzando la tecnologia compaction. La combinazione di queste funzionalità ha consentito ai clienti di ottenere risparmi fino a 5:1:1 per VSI e fino a 30:1:1 per VDI. L'ultima generazione di sistemi ONTAP include anche compressione e deduplica con accelerazione hardware, che possono migliorare ulteriormente l'efficienza dello storage e ridurre i costi. Questo approccio consente di memorizzare più dati in meno spazio, riducendo il costo complessivo dello storage e migliorando le performance. NetApp è così fiduciosa nelle sue funzionalità di efficienza dello storage che offre un link:https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [garanzia di efficienza^].
* *Locazione multipla.* ONTAP è da tempo leader nella multi-tenancy, cosa che consente di creare diverse Storage Virtual Machine (SVM) su un singolo cluster. Questo approccio consente di isolare i carichi di lavoro e fornire diversi livelli di servizio a tenant diversi, rendendolo ideale per service provider e grandi imprese. L'ultima generazione di sistemi ONTAP include anche la gestione della capacità di supporto. Questa funzionalità consente di impostare limiti di capacità per ogni tenant, in modo che nessun tenant singolo possa consumare tutte le risorse disponibili. Questo approccio aiuta a garantire che tutti i tenant ricevano il livello di servizio che si aspettano, fornendo al contempo un elevato livello di sicurezza e isolamento tra i tenant. Inoltre, le funzionalità multi-tenancy di ONTAP sono integrate nella piattaforma vSphere di VMware, consentendo di gestire e monitorare facilmente l'ambiente virtualizzato tramite https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["Strumenti ONTAP per VMware vSphere"] e https://docs.netapp.com/us-en/data-infrastructure-insights/["Informazioni sull'infrastruttura dati"].
* *Cloud ibrido.* sia che venga utilizzato per il cloud privato on-premise, l'infrastruttura di cloud pubblico o un cloud ibrido che combina il meglio di entrambi, le soluzioni ONTAP ti aiutano a costruire il tuo data fabric per ottimizzare e ottimizzare la gestione dei dati. Inizia con i sistemi all-flash dalle performance elevate, quindi accoppiali con sistemi di storage su disco o cloud per la protezione dei dati e il cloud computing. Scegli tra cloud Azure, AWS, IBM o Google per ottimizzare i costi ed evitare il lock-in. Sfrutta il supporto avanzato per le tecnologie OpenStack e container in base alle esigenze. NetApp offre inoltre backup basato sul cloud (SnapMirror Cloud, Cloud Backup Service e Cloud Sync) e tool di archiviazione e tiering dello storage (FabricPool) per ONTAP per ridurre le spese operative e sfruttare l'ampia portata del cloud.
* *E altro ancora.* sfrutta le performance estreme degli array NetApp AFF Serie A per accelerare l'infrastruttura virtualizzata e gestire i costi. Operazioni senza interruzioni, dalla manutenzione agli aggiornamenti fino alla sostituzione completa del sistema storage, utilizzando cluster ONTAP scale-out. Proteggi i dati inattivi con le funzionalità di crittografia NetApp senza costi aggiuntivi. Assicurati che le performance soddisfino i livelli di servizio di business grazie a funzionalità di qualità dei servizi. Fanno tutti parte dell'ampia gamma di funzionalità offerte da ONTAP, il software di Enterprise data management leader del settore.

