---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-settings.html 
keywords: VMware,vSphere,ESXi,settings,NFS,iSCSI,FC,FCP 
summary: Questo documento categorizza ed enumera le impostazioni di storage e di rete consigliate. 
---
= Host ESXi consigliato e altre impostazioni ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp ha sviluppato una serie di impostazioni ottimali per l'host ESXi sia per protocolli NFS sia per protocolli a blocchi. Sono inoltre fornite indicazioni specifiche per le impostazioni di multipathing e timeout HBA per un corretto comportamento con ONTAP in base ai test interni di NetApp e VMware.

Questi valori possono essere impostati facilmente utilizzando gli strumenti ONTAP per VMware vSphere: Dal dashboard Riepilogo, fare clic su Modifica impostazioni nel portlet sistemi host o fare clic con il pulsante destro del mouse sull'host in vCenter, quindi accedere a Strumenti ONTAP > Imposta valori consigliati.

Di seguito sono riportate le impostazioni dell'host consigliate per tutte le versioni di ONTAP attualmente supportate.

|===


| *Impostazione host* | *Valore consigliato da NetApp* | *Riavvio richiesto* 


3+| *Configurazione avanzata ESXi* 


| VMFS3.HardwareAcceleratedLocking | Mantieni predefinito (1) | No 


| VMFS3.EnableBlockDelete | Mantenere l'impostazione predefinita (0), ma può essere modificata se necessario. Per ulteriori informazioni, vedere link:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-provisioning-and-space-reclamation-in-vsphere/storage-space-reclamation-in-vsphere/space-reclamation-for-guest-operating-systems.html["Recupero di spazio per VMFS5 macchine virtuali"] | No 


| VMFS3.EnableVMFS6Unmap | Mantieni predefinito (1)
Per ulteriori informazioni, vedere link:https://core.vmware.com/resource/vmware-vsphere-apis-array-integration-vaai#sec9426-sub4["API VMware vSphere: Integrazione degli array (VAAI)"] | No 


3+| *Impostazioni NFS* 


| NET.TcpipelHeapSize | VSphere 6.0 o versione successiva, impostato su 32.
Tutte le altre configurazioni NFS, impostate su 30 | Sì 


| NET.TcpipelHeapMax | Impostato su 512 MB per la maggior parte delle release di vSphere 6.X.
Impostare sul valore predefinito (1024MB) per 6.5U3, 6.7U3 e 7,0 o versioni successive. | Sì 


| NFS.MaxVolumes | VSphere 6,0 o versioni successive, impostare su 256
Tutte le altre configurazioni NFS sono impostate su 64. | No 


| NFS41.MaxVolumes | VSphere 6,0 o versioni successive, impostare su 256. | No 


| NFS.MaxQueueDepth^1^ | VSphere 6.0 o versione successiva, impostato su 128 | Sì 


| NFS.HeartbeatMaxFailures | Impostare su 10 per tutte le configurazioni NFS | No 


| NFS.HeartbeatFrequency | Impostato su 12 per tutte le configurazioni NFS | No 


| NFS.HeartbeatTimeout | Impostare su 5 per tutte le configurazioni NFS. | No 


| SunRPC.MaxConnPerIP | VSphere 7,0 o versioni successive, impostare su 128. | No 


3+| *Impostazioni FC/FCoE* 


| Policy di selezione del percorso | Impostare su RR (round robin) quando si utilizzano percorsi FC con ALUA. Impostare su FISSO per tutte le altre configurazioni.
L'impostazione di questo valore su RR consente di fornire il bilanciamento del carico in tutti i percorsi attivi/ottimizzati.
Il valore FISSO è per le configurazioni precedenti non ALUA e aiuta a prevenire i/o proxy In altre parole, consente di evitare che l'i/o venga collegato all'altro nodo di una coppia ad alta disponibilità (ha) in un ambiente con Data ONTAP in 7-Mode | No 


| Disk.QFullSampleSize | Impostare su 32 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 


| Disk.QFullThreshold | Impostare su 8 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 


| Timeout HBA FC Emulex | Utilizzare il valore predefinito. | No 


| Timeout HBA FC QLogic | Utilizzare il valore predefinito. | No 


3+| *Impostazioni iSCSI* 


| Policy di selezione del percorso | Impostare su RR (round robin) per tutti i percorsi iSCSI.
L'impostazione di questo valore su RR consente di fornire il bilanciamento del carico in tutti i percorsi attivi/ottimizzati. | No 


| Disk.QFullSampleSize | Impostare su 32 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 


| Disk.QFullThreshold | Impostare su 8 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 
|===

NOTE: 1 - l'opzione di configurazione avanzata di NFS MaxQueueDepth potrebbe non funzionare come previsto quando si utilizzano VMware vSphere ESXi 7.0.1 e VMware vSphere ESXi 7.0.2. Fare riferimento a. link:https://kb.vmware.com/s/article/86331?lang=en_US["Tastiera VMware 86331"] per ulteriori informazioni.

Gli strumenti ONTAP specificano anche alcune impostazioni predefinite durante la creazione di ONTAP FlexVol Volumes e LUN:

|===


| *Strumento ONTAP* | *Impostazione predefinita* 


| Riserva di Snapshot (-percento-spazio-snapshot) | 0 


| Riserva frazionaria (-riserva frazionaria) | 0 


| Access time update (-atime-update) | Falso 


| Readahead minimo (-min-readahead) | Falso 


| Istantanee pianificate | Nessuno 


| Efficienza dello storage | Attivato 


| Garanzia di volume | Nessuno (con thin provisioning) 


| Dimensionamento automatico del volume | grow_shrink 


| Prenotazione di spazio LUN | Disattivato 


| Allocazione dello spazio del LUN | Attivato 
|===


== Impostazioni multipath per performance superiori

Sebbene non sia attualmente configurato dagli strumenti ONTAP disponibili, NetApp suggerisce le seguenti opzioni di configurazione:

* In ambienti dalle performance elevate o quando si testano le performance con un singolo datastore LUN, si consiglia di modificare l'impostazione del bilanciamento del carico del criterio di selezione del percorso (PSP) round-robin (VMW_PSP_RR) dall'impostazione IOPS predefinita di 1000 a un valore di 1. Per ulteriori informazioni, vederelink:https://knowledge.broadcom.com/external/article?legacyId=2069356["VMware KB 2069356"^].
* In vSphere 6.7 Update 1, VMware ha introdotto un nuovo meccanismo di bilanciamento del carico di latenza per la PSP Round Robin. La nuova opzione prende in considerazione la larghezza di banda i/o e la latenza del percorso quando si seleziona il percorso ottimale per i/O. Potresti trarre vantaggio dall'utilizzo in ambienti con una connettività di percorso non equivalente, ad esempio casi in cui sono presenti più nodi di rete su un percorso rispetto all'altro o quando si utilizza un sistema ASA (NetApp All SAN Array). Per ulteriori informazioni, vedere https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/understanding-multipathing-and-failover-in-the-esxi-environment/viewing-and-managing-storage-paths-on-esxi-hosts.html#GUID-1940AE9E-04CF-40BE-BB71-398621F0642E-en["Modifica dei parametri predefiniti per la latenza Round Robin"^] .




== Documentazione aggiuntiva

Per FCP e iSCSI con vSphere 7, è possibile trovare ulteriori dettagli all'indirizzo link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_7.html["Utilizzo di VMware vSphere 7.x con ONTAP"^] per FCP e iSCSI con vSphere 8. Per ulteriori dettagli, visitare la pagina link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["Utilizzo di VMware vSphere 8.x con ONTAP"^] relativa a NVMe-of con vSphere 7. Per ulteriori dettagli, visitare il sito link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_7.html["Per NVMe-of, ulteriori dettagli sono disponibili nella pagina NVMe-of host Configuration per ESXi 7.x con ONTAP"^] per NVMe-of con vSphere 8, ulteriori dettagli sono disponibili all'indirizzo link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Per NVMe-of, ulteriori dettagli sono disponibili nella pagina NVMe-of host Configuration per ESXi 8.x con ONTAP"^]
