---
sidebar: sidebar 
permalink: vmware/vmware-otv-hardening-timeout.html 
keywords: VMware, Data protection, security, OTV, Hardening, ONTAP Tools 
summary: Guida al rafforzamento della protezione per gli strumenti ONTAP per VMware vSphere. 
---
= Timeout di inattività per gli strumenti ONTAP 9,13
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per impedire l'accesso non autorizzato, viene impostato un timeout di inattività che disconnette automaticamente gli utenti inattivi per un determinato periodo di tempo durante l'utilizzo di risorse autorizzate. In questo modo, solo gli utenti autorizzati possono accedere alle risorse e mantenere la sicurezza.

* Per impostazione predefinita, le sessioni del client vSphere si chiudono dopo 120 minuti di inattività, richiedendo all'utente di accedere nuovamente per riprendere a utilizzare il client. È possibile modificare il valore di timeout modificando il file webclient.properties. È possibile configurare il timeout del client vSphere https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vcenterhost.doc/GUID-975412DE-CDCB-49A1-8E2A-0965325D33A5.html["Configurare il valore di timeout del client vSphere"]
* Gli strumenti ONTAP hanno un tempo di disconnessione della sessione Web-cli di 30 minuti.

