---
sidebar: sidebar 
permalink: vmware/vsphere/settings.html 
keywords:  
summary:  
---
= Host ESXi consigliato e altre impostazioni ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
NetApp ha sviluppato un set di impostazioni di multipathing host ESXi e timeout HBA per un comportamento corretto con ONTAP in base ai test NetApp. Questi sono facilmente impostabili utilizzando i tool ONTAP per VMware vSphere. Dalla dashboard Riepilogo, fare clic su Modifica impostazioni nel portlet sistemi host o fare clic con il pulsante destro del mouse sull'host in vCenter, quindi selezionare ONTAP Tools > Set Recommended Values (Strumenti di configurazione > Imposta valori consigliati). Di seguito sono riportate le impostazioni host attualmente consigliate per la versione 9.8.

|===


| *Impostazione host* | *Valore consigliato da NetApp* | *Riavvio richiesto* 


3+| *Configurazione avanzata ESXi* 


| VMFS3.HardwareAcceleratedLocking | Mantieni predefinito (1) | No 


| VMFS3.EnableBlockDelete | Mantenere l'impostazione predefinita (0), ma può essere modificata se necessario.
Per ulteriori informazioni, vedere link:https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2007427["Tastiera VMware 2007427"] | No 


| VMFS3.EnableVMFS6Unmap | Mantieni predefinito (1)
Per ulteriori informazioni, vedere link:https://core.vmware.com/resource/vmware-vsphere-apis-array-integration-vaai#sec9426-sub4["API VMware vSphere: Integrazione degli array (VAAI)"] | No 


3+| *Impostazioni NFS* 


| NET.TcpipelHeapSize | VSphere 6.0 o versione successiva, impostato su 32.
Tutte le altre configurazioni NFS, impostate su 30 | Sì 


| NET.TcpipelHeapMax | Impostato su 512 MB per la maggior parte delle release di vSphere 6.X.
Impostare su 1024 MB per 6.5U3, 6.7U3 e 7.0 o versioni successive. | Sì 


| NFS.MaxVolumes | VSphere 6,0 o versioni successive, impostare su 256
Tutte le altre configurazioni NFS, impostate su 64. | No 


| NFS41.MaxVolumes | VSphere 6,0 o versioni successive, impostare su 256. | No 


| NFS.MaxQueueDepth^1^ | VSphere 6.0 o versione successiva, impostato su 128 | Sì 


| NFS.HeartbeatMaxFailures | Impostare su 10 per tutte le configurazioni NFS | No 


| NFS.HeartbeatFrequency | Impostato su 12 per tutte le configurazioni NFS | No 


| NFS.HeartbeatTimeout | Impostare su 5 per tutte le configurazioni NFS. | No 


| SunRPC.MaxConnPerIP | VSphere 7,0 o versioni successive, impostare su 128. | No 


3+| *Impostazioni FC/FCoE* 


| Policy di selezione del percorso | Impostare su RR (round robin) quando si utilizzano percorsi FC con ALUA. Impostare su FISSO per tutte le altre configurazioni.
L'impostazione di questo valore su RR consente di fornire il bilanciamento del carico in tutti i percorsi attivi/ottimizzati.
Il valore FISSO è per le configurazioni precedenti non ALUA e aiuta a prevenire i/o proxy In altre parole, consente di evitare che l'i/o venga collegato all'altro nodo di una coppia ad alta disponibilità (ha) in un ambiente con Data ONTAP in 7-Mode | No 


| Disk.QFullSampleSize | Impostare su 32 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 


| Disk.QFullThreshold | Impostare su 8 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 


| Timeout HBA FC Emulex | Utilizzare il valore predefinito. | No 


| Timeout HBA FC QLogic | Utilizzare il valore predefinito. | No 


3+| *Impostazioni iSCSI* 


| Policy di selezione del percorso | Impostare su RR (round robin) per tutti i percorsi iSCSI.
L'impostazione di questo valore su RR consente di fornire il bilanciamento del carico in tutti i percorsi attivi/ottimizzati. | No 


| Disk.QFullSampleSize | Impostare su 32 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 


| Disk.QFullThreshold | Impostare su 8 per tutte le configurazioni.
L'impostazione di questo valore aiuta a prevenire gli errori di i/O. | No 
|===

NOTE: 1 - l'opzione di configurazione avanzata di NFS MaxQueueDepth potrebbe non funzionare come previsto quando si utilizzano VMware vSphere ESXi 7.0.1 e VMware vSphere ESXi 7.0.2. Fare riferimento a. link:https://kb.vmware.com/s/article/86331?lang=en_US["Tastiera VMware 86331"] per ulteriori informazioni.

Gli strumenti ONTAP specificano anche alcune impostazioni predefinite durante la creazione di ONTAP FlexVol Volumes e LUN:

|===


| *Strumento ONTAP* | *Impostazione predefinita* 


| Riserva di Snapshot (-percento-spazio-snapshot) | 0 


| Riserva frazionaria (-riserva frazionaria) | 0 


| Access time update (-atime-update) | Falso 


| Readahead minimo (-min-readahead) | Falso 


| Istantanee pianificate | Nessuno 


| Efficienza dello storage | Attivato 


| Garanzia di volume | Nessuno (con thin provisioning) 


| Dimensionamento automatico del volume | grow_shrink 


| Prenotazione di spazio LUN | Disattivato 


| Allocazione dello spazio del LUN | Attivato 
|===


== Impostazioni multipath per performance superiori

Sebbene non sia attualmente configurato dagli strumenti ONTAP disponibili, NetApp suggerisce le seguenti opzioni di configurazione:

* In ambienti dalle performance elevate o quando si testano le performance con un singolo datastore LUN, si consiglia di modificare l'impostazione del bilanciamento del carico del criterio di selezione del percorso (PSP) round-robin (VMW_PSP_RR) dall'impostazione IOPS predefinita di 1000 a un valore di 1. Consulta la Knowledge base di VMware https://kb.vmware.com/s/article/2069356["2069356"^] per ulteriori informazioni.
* In vSphere 6.7 Update 1, VMware ha introdotto un nuovo meccanismo di bilanciamento del carico di latenza per la PSP Round Robin. La nuova opzione prende in considerazione la larghezza di banda i/o e la latenza del percorso quando si seleziona il percorso ottimale per i/O. Potrebbe essere utile utilizzarlo in ambienti con connettività di percorso non equivalente, ad esempio nei casi in cui vi sono più salti di rete su un percorso rispetto a un altro, o quando si utilizza un sistema NetApp All SAN Array. Vedere https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-B7AD0CA0-CBE2-4DB4-A22C-AD323226A257.html?hWord=N4IghgNiBcIA4Gc4AIJgC4FMB2BjAniAL5A["Plug-in e policy per la selezione del percorso"^] per ulteriori informazioni.




== Documentazione aggiuntiva

Per FCP e iSCSI con vSphere 7, è possibile trovare ulteriori dettagli all'indirizzo https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_7.html["Utilizzo di VMware vSphere 7.x con ONTAP"^]
Per FCP e iSCSI con vSphere 8, è possibile trovare ulteriori dettagli all'indirizzo https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["Utilizzo di VMware vSphere 8.x con ONTAP"^]
Per NVMe-of con vSphere 7, è possibile trovare ulteriori dettagli all'indirizzo https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_7.html["Per NVMe-of, ulteriori dettagli sono disponibili nella pagina NVMe-of host Configuration per ESXi 7.x con ONTAP"^]
Per NVMe-of con vSphere 8, è possibile trovare ulteriori dettagli all'indirizzo https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Per NVMe-of, ulteriori dettagli sono disponibili nella pagina NVMe-of host Configuration per ESXi 8.x con ONTAP"^]
