---
sidebar: sidebar 
permalink: mysql/mysql-innodb_lru_scan_depth.html 
keywords: MySQL,MariaDB,innodb_lru_scan_depth 
summary: MySQL e innodb_lru_Scan_Depth 
---
= innodb_lru_scan_depth
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `innodb_lru_scan_depth` Parametro influenza gli algoritmi e le euristiche dell'operazione di scaricamento per il pool di buffer InnoDB.

Questo parametro è principalmente di interesse per gli esperti di performance che ottimizzano i carichi di lavoro i/o-intensive. Per ogni istanza del pool di buffer, questo parametro specifica fino a che punto nell'elenco di pagine LRU (Last Recently Used) il thread di pulitura della pagina deve continuare la scansione, cercando le pagine sporche da eliminare. Questa operazione in background viene eseguita una volta al secondo.

È possibile regolare il valore verso l'alto o verso il basso per ridurre al minimo il numero di pagine libere. Non impostare un valore molto superiore al necessario, poiché le scansioni possono avere un costo significativo in termini di prestazioni. Inoltre, è consigliabile regolare questo parametro quando si modifica il numero di istanze del pool di buffer, perché `innodb_lru_scan_depth * innodb_buffer_pool_instances` definisce la quantità di lavoro eseguito dal filo del pulitore di pagina ogni secondo.

Un'impostazione più piccola di quella predefinita è adatta per la maggior parte dei carichi di lavoro. Considerare l'aumento del valore solo se si dispone di capacità i/o di riserva con un workload tipico. Per contro, se un carico di lavoro con un numero elevato di operazioni di scrittura satura la capacità i/o, diminuirne il valore, soprattutto se si dispone di un pool di buffer di grandi dimensioni.
