---
sidebar: sidebar 
permalink: mysql/mysql-overview.html 
keywords: MySQL,MariaDB,TR-4722 
summary: MySQL su ONTAP 
searchtitle: MySQL su ONTAP 
---
= Panoramica
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
MySQL e le sue varianti, tra cui MariaDB e Percona MySQL, è il database più diffuso al mondo.


NOTE: Questa documentazione su ONTAP e il database MySQL sostituisce il database _TR-4722: MySQL pubblicato in precedenza sulle Best practice di ONTAP._

ONTAP è una piattaforma ideale per database MySQL, perché ONTAP è letteralmente progettato per database. Sono state create numerose funzionalità come le ottimizzazioni della latenza io random per la qualità del servizio avanzata fino alle funzionalità FlexClone di base per rispondere specificamente alle esigenze dei carichi di lavoro dei database.

Funzioni aggiuntive come gli aggiornamenti senza interruzioni, (inclusa la sostituzione dello storage) garantiscono la disponibilità dei database critici. Puoi anche disporre di un disaster recovery istantaneo per ambienti di grandi dimensioni tramite MetroCluster o selezionare database tramite la sincronizzazione attiva di SnapMirror.

Soprattutto, ONTAP offre prestazioni senza pari con la possibilità di dimensionare la soluzione in base alle proprie esigenze specifiche. I nostri sistemi high-end possono offrire oltre 1M IOPS con latenze misurate in microsecondi, ma se ti servono solo 100K IOPS, puoi dimensionare correttamente la tua soluzione storage con un controller più piccolo che esegue ancora lo stesso sistema operativo per lo storage.
