---
sidebar: sidebar 
permalink: mysql/mysql-containers.html 
keywords: MySQL,MariaDB,containers,trident 
summary: Containerizzazione di MySQL 
searchtitle: Containerizzazione di MySQL 
---
= Containerizzazione
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La containerizzazione dei database MySQL sta diventando sempre più diffusa.

La gestione di container a basso livello viene quasi sempre eseguita con Docker. Le piattaforme di gestione dei container come OpenShift e Kubernetes semplificano ulteriormente la gestione di ambienti container di grandi dimensioni. I vantaggi della containerizzazione includono una riduzione dei costi, poiché non è necessario acquistare una licenza per un hypervisor. Inoltre, i container consentono l'esecuzione di più database isolati l'uno dall'altro, condividendo lo stesso kernel e sistema operativo sottostanti. È possibile eseguire il provisioning dei container in microsecondi.

NetApp offre Astra Trident per fornire funzionalità di gestione avanzate dello storage. Ad esempio, Astra Trident consente a un container creato in Kubernetes di eseguire il provisioning automatico del proprio storage nel Tier appropriato, applicare policy di esportazione, impostare policy di snapshot e persino clonare un container in un altro. Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/trident/index.html["Documentazione di Astra Trident"^].
