---
sidebar: sidebar 
permalink: mysql/mysql-overview.html 
keywords: MySQL,MariaDB,TR-4722 
summary: MySQL su ONTAP 
---
= Database MySQL su ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL e le sue varianti, tra cui MariaDB e Percona MySQL, è il database più diffuso al mondo.


NOTE: Questa documentazione su ONTAP e il database MySQL sostituisce il database _TR-4722: MySQL pubblicato in precedenza sulle Best practice di NetApp ONTAP._

Le caratteristiche di MySQL includono:

* *TCO inferiore.* MySQL è un potente sistema di gestione di database open source, gratuito e disponibile da anni. È molto stabile. Ha il supporto della comunità che aiuta a gestire, eseguire il debug e aggiungere nuove funzionalità. Se un'applicazione Web richiede più di un database, o richiede bilanciamento del carico o sharding, è possibile configurare facilmente istanze di database con solo costi hardware, piuttosto che database commerciali che richiedono una singola licenza per ciascuna istanza.
* *Affidabilità, prestazioni e facilità d'uso.* uno dei punti di forza di MySQL è rappresentato dalle prestazioni e dalla scalabilità eccezionali, motivo per cui molte aziende basate sul Web lo utilizzano. MySQL utilizza diversi punti di forza per offrire prestazioni veloci. Poiché la concorrenza è sempre a portata di clic con il mouse (o tramite lo schermo), le risposte rapide alle domande e alle attività dei clienti sono di primaria importanza. Il database che serve applicazioni basate sul Web deve fornire prestazioni estreme sia per le operazioni di lettura (query semplici e complesse) che di scrittura.
* *Sviluppo, progettazione e amministrazione di database.* MySQL Workbench fornisce un ambiente integrato di sviluppo, progettazione e amministrazione per rendere gli sviluppatori e i DBA più produttivi. Diversi sviluppatori cercano diverse funzionalità in un database, e MySQL offre una vasta gamma di funzionalità. Può funzionare in modo adeguato sia su un notebook che su un desktop. Può adattarsi facilmente all'ambiente, assicurandosi che non collida con i server o le applicazioni web esistenti.
* *Supporto transazionale completo.* MySQL è uno dei più robusti motori di database transazionali disponibili. È la soluzione per l'integrità completa dei dati, che offre funzionalità come supporto completo di transazioni atomiche, coerenti, isolate e durevoli; supporto di transazioni multivalore; e bloccaggio illimitato a livello di fila. Fornisce l'identificazione immediata dei deadlock tramite l'integrità referenziale imposta dal server.
* *Sicurezza dei dati.* MySQL è rinomato a livello globale per essere il sistema di gestione dei database più sicuro e affidabile utilizzato nelle applicazioni web più diffuse come WordPress, Drupal, Joomla, Facebook, Google, e Twitter. La sicurezza dei dati e il supporto per l'elaborazione transazionale che accompagna la versione recente di MySQL possono avvantaggiare qualsiasi attività, in particolare le attività di e-commerce che implicano frequenti trasferimenti di denaro.
* *Architettura Pluggable.* l'architettura del motore di storage collegabile MySQL consente a un professionista di database di selezionare un motore di storage specializzato per una particolare esigenza di applicazione senza dover gestire i requisiti di codifica delle applicazioni. L'architettura server MySQL isola il programmatore di applicazioni e il DBA da tutti i dettagli di implementazione di basso livello a livello di storage, fornendo un modello applicativo e un'API coerenti e semplici. Sebbene esistano diverse funzionalità nei diversi motori di storage, l'applicazione non è schermata da queste differenze.


L'architettura efficiente e modulare di MySQL offre enormi vantaggi se si desidera soddisfare una specifica esigenza applicativa, come il data warehousing, l'elaborazione delle transazioni o situazioni di ha, utilizzando al contempo interfacce e servizi indipendenti da qualsiasi motore di storage.
