---
sidebar: sidebar 
permalink: oracle/dr/metrocluster/mc-mcc-nvfail.html 
keywords: oracle, metrocluster, extended rac, rac, nvfail, switchover 
summary: Oracle su MetroCluster - NVFAIL 
---
= MetroCluster e NVFAIL
:allow-uri-read: 


[role="lead"]
NVFAIL è una funzionalità generale di integrità dei dati di ONTAP che è particolarmente critica per il carico di lavoro del database e viene discussa in dettaglio in link:../ontap-configuration/oracle_and_nvfail.html["NVFAIL"]. Sono inoltre previste considerazioni specifiche di MetroCluster per NVFAIL.



== RAC esteso con NVFAIL forzata manualmente

L'opzione più sicura per forzare uno switchover con un cluster RAC esteso consiste nello specificare `-force-nvfail-all` alla riga di comando. Questa opzione è disponibile come misura di emergenza per assicurarsi che tutti i dati memorizzati nella cache vengano eliminati. Se un host utilizza risorse di storage situate originariamente nel sito colpito da disastro, riceve errori di i/o o un handle di file obsoleto (`ESTALE`). I database Oracle si bloccano e i file system vanno completamente offline o passano alla modalità di sola lettura.

Al termine dello switchover, il `in-nvfailed-state` Il flag deve essere cancellato e i LUN devono essere messi online. Al termine di questa attività, è possibile riavviare il database. È possibile automatizzare queste attività per ridurre l'RTO.



== RAC esteso con dr-force-nvfail

La configurazione più sicura consiste nell'impostare `dr-force-nvfail` contrassegnare tutti i volumi a cui è possibile accedere da un sito remoto. Di conseguenza, i volumi diventano non disponibili quando vengono immessi `in-nvfailed-state` durante uno switchover. Al termine dello switchover, il `in-nvfailed-state` Il flag deve essere cancellato e i LUN devono essere messi online. Al termine di queste attività, è possibile riavviare il database. È possibile automatizzare queste attività per ridurre l'RTO.

Il risultato è simile all'uso di `-force-nvfail-all` allarme. Tuttavia, il numero di volumi interessati può essere limitato solo a quei volumi che devono essere protetti da applicazioni o sistemi operativi con cache obsolete.



== RAC esteso senza dr-force-nvfail

Ci sono due requisiti critici per un ambiente che non utilizza `dr-force-nvfail` nei volumi di database:

* Uno switchover forzato non deve avvenire più di 30 secondi dopo la perdita del sito primario.
* Lo switchover non deve essere eseguito durante le attività di manutenzione o in altre condizioni in cui i plessi di SyncMirror o la replica della NVRAM non sono sincronizzati. Il primo requisito può essere soddisfatto utilizzando il software tiebreaker configurato per eseguire uno switchover entro 30 secondi da un guasto del sito. Questo requisito non significa che lo switchover debba essere eseguito entro 30 secondi dal rilevamento di un guasto del sito. Ciò significa che non è più sicuro forzare uno switchover se sono trascorsi 30 secondi da quando un sito è stato confermato operativo.


Il secondo requisito può essere parzialmente soddisfatto disattivando tutte le funzionalità di switchover automatico quando la configurazione di MetroCluster non è sincronizzata. Un'opzione migliore è quella di disporre di una soluzione di tiebreaker in grado di monitorare lo stato di salute della replica NVRAM e dei plessi SyncMirror. Se il cluster non è completamente sincronizzato, il tiebreaker non deve attivare uno switchover.

Il software NetApp MCTB non è in grado di monitorare lo stato di sincronizzazione, pertanto deve essere disattivato quando MetroCluster non è sincronizzato per alcun motivo. ClusterLion include funzionalità di monitoraggio NVRAM e plex e può essere configurato in modo da non attivare lo switchover a meno che il sistema MetroCluster non sia confermato completamente sincronizzato.
