---
sidebar: sidebar 
permalink: oracle/dr/metrocluster/oracle-failover-on-metrocluster.html 
keywords: Metrocluster, mcc, MCC-IP 
summary: Oracle con MetroCluster 
---
= Failover di Oracle con MetroCluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../../media/


[role="lead"]
L'utilizzo di MetroCluster non aggiunge né modifica necessariamente le Best practice per il funzionamento di applicazioni e database aziendali.

Le normali Best practice vengono comunque applicate e se le tue esigenze richiedono solo RPO=0:1 di data Protection, allora MetroCluster ne soddisfa l'esigenza. Tuttavia, la maggior parte dei clienti utilizza MetroCluster non solo per la protezione dei dati con RPO=0, ma anche per migliorare l'RTO in scenari di disastro, oltre a fornire un failover trasparente come parte delle attività di manutenzione del sito.



== Failover con un sistema operativo preconfigurato

SyncMirror fornisce una copia sincrona dei dati nel sito di disaster recovery, ma per renderli disponibili sono necessari un sistema operativo e le applicazioni associate. L'automazione di base può migliorare notevolmente il tempo di failover dell'ambiente complessivo. I prodotti Clusterware come Oracle RAC, Veritas Cluster Server (VCS) o VMware ha vengono spesso utilizzati per creare un cluster in tutti i siti, e in molti casi il processo di failover può essere guidato da semplici script.

In caso di perdita dei nodi primari, il clusterware (o gli script) viene configurato in modo da portare le applicazioni online nel sito alternativo. Un'opzione è creare server di standby preconfigurati per le risorse NFS o SAN che costituiscono l'applicazione. Se il sito primario non funziona, il clusterware o l'alternativa con script esegue una sequenza di azioni simile alle seguenti:

. Forzare uno switchover su MetroCluster
. Rilevamento di LUN FC (solo SAN)
. Montaggio di file system
. Avvio dell'applicazione


Il requisito principale di questo approccio è rappresentato da un sistema operativo in esecuzione sul sito remoto. Deve essere preconfigurato con file binari delle applicazioni, il che significa anche che attività come l'applicazione di patch devono essere eseguite sul sito primario e di standby. In alternativa, è possibile eseguire il mirroring dei file binari dell'applicazione nel sito remoto e montarli se viene dichiarato un disastro.

La procedura di attivazione effettiva è semplice. Comandi come il rilevamento delle LUN richiedono solo pochi comandi per ogni porta FC. Il montaggio del file system non è altro che un `mount` E sia i database che ASM possono essere avviati e arrestati dalla CLI con un unico comando. Se i volumi e i file system non vengono utilizzati nel sito di disaster recovery prima dello switchover, non è necessario impostare alcun requisito `dr-force- nvfail` sui volumi.



== Failover con un sistema operativo virtualizzato

Il failover degli ambienti di database può essere esteso per includere il sistema operativo stesso. In teoria, questo failover può essere eseguito con le LUN di avvio, ma nella maggior parte dei casi con un sistema operativo virtualizzato. La procedura è simile ai seguenti passaggi:

. Forzare uno switchover su MetroCluster
. Montaggio dei datastore che ospitano le macchine virtuali del server di database
. Avvio delle macchine virtuali
. Avviare i database manualmente o configurare le macchine virtuali per avviare automaticamente i database


Ad esempio, un cluster ESX può estendersi su diversi siti. In caso di disastro, dopo lo switchover, è possibile portare online le macchine virtuali nel sito di disaster recovery. Fino a quando i datastore che ospitano i database server virtualizzati non saranno in uso in occasione di un evento di emergenza, non sarà necessario impostare alcun valore `dr-force- nvfail` sui volumi associati.
