---
sidebar: sidebar 
permalink: postgres/postgres-appendix-a.html 
keywords: PostgreSQL,database,postgres 
summary: Database PostgreSQL su ONTAP 
---
= Appendice A: Configurazione degli host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Contenuto dell'appendice:

* Verificare che gli adattatori bus host FC (HBA) nell'host ESX siano in esecuzione con driver, firmware e versione del BIOS aggiornati.
* Installare le utilità host NetApp sull'host per visualizzare i percorsi diretti e indiretti per un determinato LUN. Il kit fornisce anche informazioni estese sulle informazioni LUN SVM.
* Utilizzare sempre uno script del bus SCSI Rescan sull'host per:
* Trova nuovi LUN
* Eliminare i LUN obsoleti
* Aggiorna nuovi percorsi ai LUN
* Per stabilire più percorsi per lo storage in caso di errore di percorso, installare e configurare il software multipathing sul sistema operativo host.
* Se non si utilizza software multipath, occorre limitare ogni LUN a un singolo percorso.
* Il kernel Linux permette un controllo di basso livello sulla pianificazione di i/o per bloccare i dispositivi. Le impostazioni predefinite nelle versioni Linux potrebbero variare notevolmente. In generale, i clienti NetApp e i test interni mostrano risultati migliori con l'utilità di pianificazione NoOps per i database. Devi eseguire un'analisi comparativa per determinare quali scheduler i/o sono ottimali per il tuo caso d'utilizzo.

