---
sidebar: sidebar 
permalink: postgres/postgres-snapshot-dp.html 
keywords: PostgreSQL,database,postgres 
summary: Database PostgreSQL e snapshot di storage 
---
= Database PostgreSQL e snapshot di storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
I backup basati su snapshot con PostgreSQL richiedono la configurazione di snapshot per file di dati, file WAL e file WAL archiviati per garantire un ripristino completo o point-in-time.

Per i database PostgreSQL, il tempo medio di backup con gli snapshot è compreso tra pochi secondi e pochi minuti. Questa velocità di backup è da 60 a 100 volte più veloce di `pg_basebackup` e altri approcci di backup basati sul file system.

Le snapshot sullo storage NetApp possono essere coerenti con il crash e con l'applicazione. Viene creato uno snapshot coerente con i crash sullo storage senza chiudere il database, mentre uno snapshot coerente con l'applicazione viene creato mentre il database è in modalità backup. NetApp garantisce inoltre che le snapshot successive siano backup incrementali perenni, per promuovere il risparmio dello storage e l'efficienza della rete.

Poiché le snapshot sono rapide e non influiscono sulle prestazioni del sistema, è possibile pianificare snapshot multiple ogni giorno invece di creare un unico backup giornaliero come avviene con l'altra tecnologia di backup in streaming. Quando è necessaria un'operazione di ripristino e ripristino, il downtime del sistema viene ridotto da due caratteristiche principali:

* La tecnologia di recovery di dati NetApp SnapRestore consente di eseguire l'operazione di ripristino in pochi secondi.
* Obiettivi di recovery point (RPO) aggressivi richiedono l'applicazione di un numero inferiore di log dei database e un'accelerazione del recovery in avanti.


Per eseguire il backup di PostgreSQL, è necessario assicurarsi che i volumi di dati siano protetti contemporaneamente con WAL (gruppo di coerenza) e i registri archiviati. Mentre si utilizza la tecnologia Snapshot per copiare i file WAL, assicurarsi di eseguire `pg_stop` Per svuotare tutte le voci WAL che devono essere archiviate. Se si svuotano le voci WAL durante il ripristino, sarà sufficiente arrestare il database, smontare o eliminare la directory dei dati esistente ed eseguire un'operazione SnapRestore sull'archiviazione. Al termine del ripristino, è possibile montare il sistema e riportarlo allo stato corrente. Per il ripristino point-in-time, è anche possibile ripristinare i registri WAL e di archivio; quindi PostgreSQL decide il punto più coerente e lo recupera automaticamente.

I gruppi di coerenza sono una funzionalità di ONTAP e sono consigliati quando ci sono più volumi montati su una singola istanza o su un database con tablespace multiple. Uno snapshot del gruppo di coerenza garantisce che tutti i volumi siano raggruppati e protetti. È possibile gestire in modo efficiente un gruppo di coerenza da ONTAP System Manager, clonandolo per creare una copia dell'istanza di un database a scopo di test o sviluppo.
