---
sidebar: sidebar 
permalink: postgres/postgres-native-dp.html 
keywords: PostgreSQL,database,postgres 
summary: Protezione dei dati PostgreSQL 
searchtitle: Protezione dei dati nativa di PostgreSQL 
---
= Protezione DDTA nativa
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Uno degli aspetti principali della progettazione dello storage è la protezione dei volumi PostgreSQL. I clienti possono proteggere i database PostgreSQL utilizzando l'approccio dump o i backup del file system. In questa sezione vengono illustrati i diversi approcci per il backup di singoli database o dell'intero cluster.

Sono disponibili tre approcci per il backup dei dati PostgreSQL:

* Dump di SQL Server
* Backup a livello di file system
* Archiviazione continua


L'idea alla base del metodo dump di SQL Server è generare un file con comandi di SQL Server che, quando viene restituito al server, può ricreare il database così come era al momento del dump. PostgreSQL fornisce i programmi di utilità `pg_dump` e. `pg_dump_all` per la creazione di backup singolo e a livello di cluster. Questi dump sono logici e non contengono informazioni sufficienti per essere utilizzati da WAL Replay.

Una strategia di backup alternativa consiste nell'utilizzare il backup a livello di file system, in cui gli amministratori copiano direttamente i file utilizzati da PostgreSQL per memorizzare i dati nel database. Questo metodo viene eseguito in modalità non in linea: Il database o il cluster devono essere chiusi. Un'altra alternativa è quella di utilizzare `pg_basebackup` Per eseguire il backup hot streaming del database PostgreSQL.
